### ISSUE TITLE
Ability to see which commit id was last applied

### ISSUE THREAD

**Issue by etsauer** [KohlsTechnology/eunomia#101]
I would like the ability to see which git commit id was last run. We could add this two places:

1. In the logs of the job pod, both at the beginning and at the end of a run.
2. In the `.status` section of the `GitOpsConfig` resource being acted on.

**Comment by seanmalloy** [comment]
I believe we would want to add this to the `.status` section on the `GitOpsConfig` resources.

**Comment by seanmalloy** [comment]
For the `.status` section in the `GitOpsConfig` resource I'm thinking we would want the below fields.

* a field for the Git SHA1 that is currently being applied
* a field for the last successfully applied git SHA1
* a state field that can have it's value set to Success, InProgress, or Failure that represents the state of the k8s job
* a start timestamp field that represents when the latest k8s job started
* an end timestamp field that represents when the latest k8s job ended

I'd be interested what other people think about the above list of suggested fields.

**Comment by seanmalloy** [comment]
The initial `.status` fields were added in #163, but we still have not added the details git fields to the `.status`.
