### ISSUE TITLE
Tests should not rely on connectivity to the internet

### ISSUE THREAD

**Issue by etsauer** [KohlsTechnology/eunomia#12]
When we write e2e tests, we should attempt to decouple the tests from having connectivity to the repo. Not all working environments will have internet access, so we should write our tests to run "disconnected". I believe we could accomplish this by running a git server (e.g. Gogs) in our local test cluster.

## What happens?

Test fails, as the job is unable to pull the repository content.

## What were you expecting to happen?

Test should succeed.

## Steps to reproduce: 

* Turn off wifi
* Run `./e2e-test.sh`

## Any errors, stacktrace, logs? 

```
INFO[0000] Testing operator locally.                    
test &{{ } {gitops  test-gitops-operator /apis/eunomia.kohls.io/v1alpha1/namespaces/test-gitops-operator/gitopsconfigs/gitops 183ba73d-827a-11e9-be41-441d546aa67b 9415 1 2019-05-29 21:27:31 -0400 EDT <nil> <nil> map[] map[gitopsconfig.eunomia.kohls.io/initialized:true] [] nil [] } {{https://github.com/KohlsTechnology/eunomia master    example/templates } {https://github.com/KohlsTechnology/eunomia master    example/parameters } [{Change  }] gitops-operator quay.io/kohlstechnology/eunomia-ocp-templates:v0.0.1 CreateOrMerge Delete} {}}+--- FAIL: TestOCPTemplate (60.07s)
	client.go:57: resource type GitOpsConfig with namespace/name (test-gitops-operator/gitops) created
	util.go:38: Waiting for availability of hello-openshift pod
	util.go:38: Waiting for availability of hello-openshift pod
	util.go:38: Waiting for availability of hello-openshift pod
	util.go:38: Waiting for availability of hello-openshift pod
	util.go:38: Waiting for availability of hello-openshift pod
	util.go:38: Waiting for availability of hello-openshift pod
	util.go:38: Waiting for availability of hello-openshift pod
	util.go:38: Waiting for availability of hello-openshift pod
	util.go:38: Waiting for availability of hello-openshift pod
	util.go:38: Waiting for availability of hello-openshift pod
	util.go:38: Waiting for availability of hello-openshift pod
	util.go:38: Waiting for availability of hello-openshift pod
	util.go:38: Waiting for availability of hello-openshift pod
	ocp_template_test.go:48: timed out waiting for the condition
	client.go:75: resource type GitOpsConfig with namespace/name (test-gitops-operator/gitops) successfully deleted
FAIL
FAIL	github.com/KohlsTechnology/eunomia/test/e2e	60.183s
Error: failed to exec []string{"go", "test", "./test/e2e/...", "-namespacedMan", "deploy/test/empty.yaml", "-globalMan", "deploy/test/empty.yaml", "-root", "/home/esauer/go/src/github.com/KohlsTechnology/eunomia", "-singleNamespace", "-parallel=1"}: exit status 1
```

## Environment:

* Runtime version(Java, Go, Python, etc): `go version go1.10.8 linux/amd64`
* Desktop OS/version: Fedora 29

## Additional comments:

...

**Comment by raffaelespazzoli** [comment]
is this a strong requirement? for example we always assume we can download images from internet. if we cannot assume that we then have to change how images are pushed to presumably a local repo. All manifests for testing will have to take that into account...

**Comment by cnuland** [comment]
@etsauer would we have images built on the fly then as well for things like the template engines and test images? I'm concerned that increases the complexity of maintaining the test framework in a CI process. I do see where you're coming from though, maybe worth a chat  sometime with @raffaelespazzoli and myself to discuss further?
