### ISSUE TITLE
Standalone `go test ./...` should Just Work™️

### ISSUE THREAD

**Issue by akavel** [KohlsTechnology/eunomia#126]
Currently, tests require being run with `./scripts/e2e-tests.sh` or `./scripts/unit-tests.sh`. Standalone `go test ./...`, or even `go test ./pkg/...`, doesn't work. 

## What happens?
```
$ go test ./... > /dev/null && echo ok || echo fail
fail
$ go test ./pkg/... > /dev/null && echo ok || echo fail
fail
$ ./scripts/unit-tests.sh > /dev/null && echo ok || echo fail
ok
```

## What were you expecting to happen?
```
$ go test ./... > /dev/null && echo ok || echo fail
ok
```

## Additional comments:

Suggested approach:

 1. Move the env values from `unit-tests.sh` into Go code, possibly to be set via some helper package if they are really needed in more than 1 package in tests. If there is a need to set them to something else somewhere else (in Travis? are they used somewhere else?), provide a way to override them (e.g. via env)
 2. Change the tests in `./test/` to not run by default (for example, by [marking them with a build tag](https://dave.cheney.net/2013/10/12/how-to-use-conditional-compilation-with-the-go-build-tool), e.g. `e2e`), then modify `e2e-tests.sh` to enable running them (for example, by enabling the `e2e` build tag).

**Comment by seanmalloy** [comment]
@sbar95 regarding our conversation earlier today. Let's try to first get just the unit tests working with `go test` without using the wrapper. Build tags can be used to ignore the e2e tests for now. Just submit a PR for these minimal changes first.

Once the above is working then we can research if we want to stick with using the operator-sdk e2e test framework or just use `go test` for e2e tests.

**Comment by sbar95** [comment]
@seanmalloy I've submitted a PR for these minimal changes. Now I'm going to research further if we can replace operator-sdk with go test.

**Comment by sbar95** [comment]
@seanmalloy It's possible [to not use](https://github.com/operator-framework/operator-sdk/blob/v0.8.1/doc/test-framework/writing-e2e-tests.md#running-go-test-directly-not-recommended) `operator-sdk test local` command. I'll try to implement it.

**Comment by sbar95** [comment]
So far I managed to replace `operator-sdk test local ...` with `go test ...` in `e2e-test.sh`. I'm trying to come up with a solution to get rid of the script completely in favor of `go test`.

**Comment by seanmalloy** [comment]
The unit tests have been updated to use just plain old `go test`. At this time we are going to use the e2e test functionality provided by the `operator-sdk`.
