### ISSUE TITLE
During development, use `pullPolicy: IfNotPresent` in deploy/helm/

### ISSUE THREAD

**Issue by akavel** [KohlsTechnology/eunomia#127]
In https://github.com/KohlsTechnology/eunomia/blob/a33438224bf3d02c1ac61c26303d5647b53a1d12/deploy/helm/operator/values.yaml#L13  a different pull policy should be used when:

  - a) we publish a helm chart — use `Always`, so that end-users would have the latest official release of eunomia;
  - b) developing locally — use `IfNotPresent`, so that developers could push a development, unpublished image into kubernetes for testing.

## What happens?
During development, I push a locally built image of eunomia to minikube's docker repository (loaded with `eval $(minikube docker-env)`) then build and tag a `quay.io/kohlstechnology/eunomia-operator:latest` docker image. After running `helm template deploy/helm/operator/ | kubectl apply -f -`, the eunomia-operator image I pushed is ignored, and an official image is downloaded from quay.io instead.

## What were you expecting to happen?
I expected that my development image would be used, and not get overwritten by the official image.

**Comment by Smiley73** [comment]
We made a lot of bad experiences in the past using `latest` for example. If you use a specific release that then this is fine, but `latest` or `dev` will require `always` outside of a minikube environment.
Background: It'`ll see you're using the `latest` tag and not pull the latest image even though there might be a new one, because it already has `latest` cached locally.

**Comment by akavel** [comment]
@mkyc What's your opinion on that?

**Comment by mkyc** [comment]
In PR https://github.com/KohlsTechnology/eunomia/pull/120 I have good example which should be able to solve it smoothly. We could have two files: values.yaml and values.yaml.tpl. First one with value `IfNotPresent` and a second one with either placeholder or with `Always`. During release build we generate values.yaml from values.yaml.tpl (we overwrite original one). With this setup (in mentioned PR it's used with Chart.yaml/Chart.yaml.tpl pair) we have both situations done.
