### ISSUE TITLE
Push Container Images to Quay

### ISSUE THREAD

**Issue by seanmalloy** [KohlsTechnology/eunomia#13]
## What happens?

Container images for this project are not available on a public container registry.

## What were you expecting to happen?

Container images for this project are pushed to https://quay.io/organization/kohlstechnology

## Steps to reproduce: 

Look at https://quay.io/organization/kohlstechnology, notice that the container images for this project do not exist.

## Any errors, stacktrace, logs? 

N/A

## Environment:

* Runtime version(Java, Go, Python, etc): n/a
* Desktop OS/version: n/a

## Additional comments:

none

**Comment by cnuland** [comment]
@seanmalloy can we mark this as done?

**Comment by seanmalloy** [comment]
This was completed a while ago, so closing it now.
