### ISSUE TITLE
Gitconfig files are not copied to home directory

### ISSUE THREAD

**Issue by mathianasj** [KohlsTechnology/eunomia#130]
(While submitting an issue briefly describe the problem you are facing or a new feature you would want to see added) 

## What happens?
I try to set git config files but they do not copy to the home directory
...

## What were you expecting to happen?
The files copy so that auth can be used for a protected git repo
...

## Steps to reproduce: 

* Setup git auth per the readme file
* Create a gitopsconfig and watch the job fail that it cannot find a password

## Any errors, stacktrace, logs? 

...

## Environment:

* Runtime version(Java, Go, Python, etc): ansible applier
* Desktop OS/version: Mac

## Additional comments:
Have a PR to address the issue
...

**Comment by seanmalloy** [comment]
Fixed by #195
