### ISSUE TITLE
Run all examples as part of real e2e tests

### ISSUE THREAD

**Issue by akavel** [KohlsTechnology/eunomia#133]
`./scripts/e2e-test.sh` should run all scenarios from `./examples/`; current e2e-test.sh has way too small coverage of the code, didn't catch a lot of bugs we had, and many new developments are still not covered by it.

## What happens?

Running `./scripts/e2e-test.sh` did not tell us about #115 — all tests were passing, though delete functionality was broken. The example scenarios include running the delete functionality, but e2e-test.sh was passing successfully when delete was broken.

Also, `./examples/hello-world-yaml` was failing previously on my dev machine, whereas e2e-test.sh still was passing successfully.

## What were you expecting to happen?

- [x] `./scripts/e2e-test.sh` should run all scenarios from `./examples/`
    - for example, it should be failing when hello-world-yaml is failing
- [ ] when any examples are changed (including changes in the commands in `./examples/*/README.md`), the e2e-test.sh should automatically update (for example, by automatically extracting the commands to run from the README.md files)
- [x] `./scripts/e2e-test.sh` must then pass in Travis-CI

## Steps to reproduce: 

* change something in `./examples/hello-world-helm/` (or `-yaml/`) to make it broken
* run hello-world-helm (or -yaml) example to verify it is broken
* run `./scripts/e2e-test.sh` — observe that it still reports success

**Comment by akavel** [comment]
@seanmalloy You wrote should *NOT* be run out of the `examples` directory? I don't think I understand; I believe this issue suggests to run them *from* the `examples` directory...

**Comment by seanmalloy** [comment]
I'm saying that all e2e tests should probably be moved to a different directory. We need two different directories. One for examples and one for e2e tests.

We probably need to track moving e2e tests in a separate issue.

**Comment by seanmalloy** [comment]
We still need to implement the checklist item number 2 ... `when any examples are changed the e2e-test.sh should automatically update`
