### ISSUE TITLE
Ability to pass arguments to template processors

### ISSUE THREAD

**Issue by etsauer** [KohlsTechnology/eunomia#134]
Wanted to propose the feature before I start working on it.

I occasionally have a need to be able to pass additional arguments/flags to the template processor I am using, such as `oc process --ignore-unknown-parameters` or `ansible-playbook -e filter_tags=foo`.

What I would propose for this is to add a new field `.spec.templateProcessorArgs` to a GitOpsConfig, which would populate a new env var in the job templates. Then each template processor image can handle (or not) that env var appropriately.

Let me know if this sounds reasonable and i will start working on a PR.

**Comment by seanmalloy** [comment]
@etsauer I think this feature sounds reasonable.

**Comment by vinny-sabatini** [comment]
Hey @etsauer , I was hoping to use this functionality as well in my upcoming pull request, do you have any idea when you're hoping to work on/complete this?
