### ISSUE TITLE
Switch resource handling mode to annotations

### ISSUE THREAD

**Issue by Smiley73** [KohlsTechnology/eunomia#153]
**Is your feature request related to a problem? Please describe.**
The current way of handling the different resource handling modes (create, delete, patch, ...) would require separate gitopsconfigs, parameters, and templates for each one. This does not scale at all and makes for a very bad user experience.

**Describe the solution you'd like**
Add an optional annotation to each yaml document, to set the desire mode. It should default to 'apply'.

**Describe alternatives you've considered**
Open for other suggestions.

**What version of eunomia are you using?**
eunomia version: 0.0.3

**Additional context**
N/A

**Comment by akavel** [comment]
Would "Apply" be the new name of "CreateOrMerge"? or do I misunderstand some things?

**Comment by seanmalloy** [comment]
@akavel I believe you are correct. `Apply` would be the new name for `CreateOrMerge` if we go with this approach.

**Comment by seanmalloy** [comment]
The annotation that will be used is `metadata.eunomia.kohls.io/action`. The supported actions are listed below.

* apply - Use `kubectl apply` 
* create - Use `kubectl create`
* delete - Use `kubectl delete`
* patch - Use `kubectl patch`
* replace - Use kubectl replace`

If the annotation `metadata.eunomia.kohls.io/action` is not found on k8s YAML manifests then the action that is defined in the `GitOpsConfig` CR should be used.

**Comment by akavel** [comment]
Some particular features I'm not yet 100% sure how it should interact with, so I think it would be good to clarify:

 1. How would this interact with **automatic detection of removed resources** (#24)? — to be clarified for every one of the annotations
    - *my initial proposal for discussion:* limit #24 to only work for resources managed with `apply`
 2. How would this interact with **non-kubectl template processors**? (so, esp. the ones which hijack the resource management step)
    - *my initial proposal for discussion:* leave the decision to particular templ. processor; with a recommendation to support at least `apply`, and that handling of others can be claimed as undefined, or as ignored with a warning in logs (preferable, but harder to implement)

**Comment by Smiley73** [comment]
Since this is a breaking change, all test cases and examples will have to be updates as part of this issue. I'd also recommend using a new parameter name like `defaultAction` in the CR
To @akavel 's question on non-kubectl processors: I believe the openshift-applier is the only one currently and they set the mode to `None`. We need to just keep supporting that.

**Comment by seanmalloy** [comment]
I'm going to setup some time with @sanbornick next week to do a white board design session. We will report back on this issue with a full design proposal.

I'm thinking this feature will need to be pushed back to the v0.0.6 milestone.
