### ISSUE TITLE
Upgrade to latest version on operator-sdk

### ISSUE THREAD

**Issue by Smiley73** [KohlsTechnology/eunomia#167]
**Describe the solution you'd like**
Upgrade the code to support the latest operator-sdk.

**Describe alternatives you've considered**
Stick with the old and create more technical debt.

**What version of eunomia are you using?**
eunomia version: 0.0.x

**Comment by Smiley73** [comment]
@seanmalloy this is not part of a milestone and we're using a very outdated version of the operator. I'm using a much newer version locally and it seems to be working fine. Not sure if this could also be the root cause for the build problems on PR #243 .

**Comment by seanmalloy** [comment]
@Smiley73 first we need to upgrade to Go 1.13, see #246. After that we can upgrade to that latest version of the operator-sdk.

From my perspective we need to ...

1. Build out more test automation and get more bugs fixed
2. Update to Go 1.13
3. Update to latest version of operator-sdk

**Comment by Smiley73** [comment]
@seanmalloy I'm using 1.13 & a later operator-sdk at home for eunomia. I think you're overestimating the effort to do this. I've not experienced any issues.

**Comment by akavel** [comment]
When doing this, we should also check if we can then disable all use of `vendor` directory from the repository (including from `.gitignore` and any `go mod vendor` calls), and suggest to every developer to delete it from their machine. It would be a welcome simplification and cleanup.

**Comment by seanmalloy** [comment]
The project has been upgraded to Go 1.13. We also now have a proper test matrix in Travis CI for testing against multiple k8s and OpenShift versions.

We are now all clear to upgrade to a newer version of operator-sdk. I added this issue to the near-term milestone. If someone has bandwidth to pick this up that would be great.
