### ISSUE TITLE
Start using golang.org/x/xerrors instead of raw `return err`

### ISSUE THREAD

**Issue by akavel** [KohlsTechnology/eunomia#178]
**Is your feature request related to a problem? Please describe.**

I am wary of the way how errors are currently returned from functions in the codebase — for example, code blocks like below:

```go
if err != nil {
    log.Error(err, "...<some message>...", "foo", bar)
    return err
}
```

As much as I understand the value of structured logs, I'm especially uncomfortable with the "naked" `return err`. This isn't a good practice in Go, in part because it loses information for tracking the details of the problem at intermediate steps, when the error finally surfaces somewhere higher.

**Describe the solution you'd like**

I suggest using https://golang.org/x/xerrors package, and through its [Errorf](https://godoc.org/golang.org/x/xerrors#Errorf) function, adding helpful context information when returning an error, instead of a raw `return err`.

**Describe alternatives you've considered**

I considered also removing `log.Error` calls; but I think those can be still useful for getting information in a more structured way (JSON), better for bulk log analysis than the format used in xerrors. 

**What version of eunomia are you using?**

eunomia version: 0.0.4 / dev

**Additional context**

**Comment by sbar95** [comment]
I'll let myself attach a [blog post](https://dave.cheney.net/2015/11/05/lets-talk-about-logging) about go logging here. It's about log levels - I came across it while looking for a way to set a warning level in a log message. After reading it I decided not to do so.

**Comment by akavel** [comment]
@sbar95 Can you help me understand what specific ideas / arguments you want to convey through this link, *with regards to the particular issue that's being discussed here?*

**Comment by sbar95** [comment]
Just wanted to state that coming from background other than golang I was surprised by the way error handling is done here (just errors and info). Also, it discusses code snippet very similar to that you posted and says why it's bad practice. As your issue concerns good practice in go I thought the link might be helpful. Though, it might be too general for this issue.

**Comment by akavel** [comment]
@sbar95 This is an interesting article; however, I'd like to keep this issue laser-focused on a much smaller and simpler matter: of using xerrors. If you would like to discuss the way how logging is done in eunomia, I'd be grateful if you could open a new separate issue. I understand now that I miswrote this issue a bit, unnecessarily mentioning logging; I will try to edit it to make my intentions more clear. Thanks!

**Comment by seanmalloy** [comment]
I think we can look into using xerrors after the v0.1.0 release.
