### ISSUE TITLE
chore: add a CI test for copyright headers

### ISSUE THREAD

**Issue by akavel** [KohlsTechnology/eunomia#181]
**Is your feature request related to a problem? Please describe.**

I'm always frustrated when in reviews, I remind people about adding a copyright header. I want to focus on more important things, and this is something that could be done mechanically by a script, *if we do have such a policy*. It would then have the benefit of not relying on people (contributors & reviewers) remembering about this.

**Describe the solution you'd like**

A script in CI pipeline would check if a proper copyright header is added

- in .go files
- ideally, also in bash scripts, though this may be harder to detect

Maybe there's already some GitHub bot doing this that we could subscribe to, for doing it fast and cheap?

**Describe alternatives you've considered**

- keeping doing as is, and sometimes forgetting about the header both by contributor and reviewer
- making this a non-mandatory CI test (a "warning") - not sure which way is better; if not this, maybe the test should still have an option for per-file opt-out if needed?

**What version of eunomia are you using?**

eunomia version: 0.0.4

**Additional context**

**Comment by seanmalloy** [comment]
I like this idea! I think we can take a look at this after the v0.1.0 release.
