### ISSUE TITLE
Hierarchy fails on empty directory

### ISSUE THREAD

**Issue by Fuzzy042** [KohlsTechnology/eunomia#184]
**What version of eunomia are you using?**

eunomia version: 0.0.4

**Does this issue reproduce with the latest release?**
yes

**What operating system and processor architecture are you using (`kubectl version`)?**
jinja

**What did you do?**
When you have an empty directory as part of the hierarchy is fails on yq merge stating that 2 or more yaml files are needed.

The following line needs to be skipped if no yaml files were found in folder.
https://github.com/KohlsTechnology/eunomia/blob/2e4618d13135de18cb1b4083772f02b1f9aef85c/template-processors/base/bin/processParameters.sh#L54

**What did you expect to see?**
Empty folders skipped with processing continuing to merge other files found.

**What did you see instead?**
Error where processing stopped.

**Comment by seanmalloy** [comment]
@Fuzzy042 thanks for the bug report! I've added this to the v0.0.6 milestone.
