### ISSUE TITLE
Make e2e Tests Work

### ISSUE THREAD

**Issue by seanmalloy** [KohlsTechnology/eunomia#19]
## What happens?

e2e tests are not currently working.

## What were you expecting to happen?

e2e tests work and are integrated with Travis CI.

## Steps to reproduce: 

n/a

## Any errors, stacktrace, logs? 

n/a

## Environment:

* Runtime version(Java, Go, Python, etc): n/a
* Desktop OS/version: n/a

## Additional comments:

none

**Comment by cnuland** [comment]
@seanmalloy could this be split into two issues, one for making it work and another to add travis integration? One I see as a defect and another I see as a high priority feature request.

**Comment by seanmalloy** [comment]
@cnuland yes this is fine. We can split this into two separate issues.
