### ISSUE TITLE
Error is logged with severity: "INFO" and Info like log lines are logged with severity: ERROR"

### ISSUE THREAD

**Issue by tomsucho** [KohlsTechnology/eunomia#190]
**What version of eunomia are you using?**

eunomia version:
v0.0.4
**Does this issue reproduce with the latest release?**
yes

**What operating system and processor architecture are you using (`kubectl version`)?**

<details><summary><code>kubectl version</code> Output</summary><br><pre>
```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.8", GitCommit:"211047e9a1922595eaa3a1127ed365e9299a6c23", GitTreeState:"clean", BuildDate:"2019-10-15T12:11:03Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.8-gke.12", GitCommit:"188432a69210ca32cafded81b4dd1c063720cac0", GitTreeState:"clean", BuildDate:"2019-11-07T19:27:01Z", GoVersion:"go1.12.11b4", Compiler:"gc", Platform:"linux/amd64"}
```
</pre></details>

**What did you do?**
deployed gitops cr on the project namespace in a GKE cluster.

**What did you expect to see?**
Errors log lines having severity ERROR
Info like log lines with severity INFO

**What did you see instead?**
While examining GKE stackdriver logs from the POD I see the following:
Error log line with severity INFO
Info log lines with severity ERROR

It looks to me that all what goes out due to bash set -x is severity ERROR (as that goes to stderr I think) and all what just goes out to stdout gets INFO, even if it contains an ERROR msg actually. Can provide example log if you need it in private channel.

**Comment by akavel** [comment]
Can't this be reconfigured somehow in stackdriver? Personally, I wouldn't want to lose the ability of seeing the `set -x` log output from our scripts — it's a very useful debugging tool... Do you by chance have any ideas (even brainstorm-grade random ones) regarding what we could try to do to improve the situation in stackdriver, while ideally keeping as much insight into the scripts' work as possible?

**Comment by tomsucho** [comment]
I don't know of any easy way to fix this. The culprit is the 'set -x' here which sends all to stderr and GKE (and all systems in general) will treat this as ERR log level. I don't think there's a way to reconfigure this behaviour. Disabling set -x at some stage and leaving only the logging echo's for the important parts of the script should be enough in my view.
