### ISSUE TITLE
Finalize Resource Handling Modes For v1alpha1

### ISSUE THREAD

**Issue by seanmalloy** [KohlsTechnology/eunomia#203]
**Is your feature request related to a problem? Please describe.**

The `CreateOrMerge` resource handling mode is confusing. It should be removed.

**Describe the solution you'd like**

Remove the `CreateOrMerge` resource handling mode. It should be replaced by two new resource handling modes `Apply` and `Create`. The `Apply` resource handling mode will run `kubectl apply`. The `Create` resource handling mode will run `kubectl create`.

**EDIT:** We also need the `Replace` and `Delete` resource handling modes. These will run `kubectl repalce` and `kubectl delete`.

**Describe alternatives you've considered**

I have not considered any alternatives.

**What version of eunomia are you using?**

eunomia version: v0.0.5

**Additional context**

We removed the `CreateOrUpdate` resource handling mode in #149.

**Comment by akavel** [comment]
How about the additional `Replace` and `Delete` modes suggested by @sanbornick IIRC? What problem does `Create` solve if there's no `Replace` and `Delete` as well?

**Comment by seanmalloy** [comment]
@akavel I discussed with @sanbornick and confirmed that we want to add the `Replace` and `Delete` resource handling modes. Thanks!
