### ISSUE TITLE
With "Change" trigger new job is spawned each 10 seconds

### ISSUE THREAD

**Issue by sbar95** [KohlsTechnology/eunomia#206]
**What version of eunomia are you using?**

eunomia version: dev after v0.0.5 (the last commit is 5bd669dbe3793bbefe959a03c1ae21dbf2706594)

**Does this issue reproduce with the latest release?**

No, in the latest release there is another issue: #199 which is already repaired in dev (so also in the code I'm using).

**What operating system and processor architecture are you using (`kubectl version`)?**

<details><summary><code>kubectl version</code> Output</summary><br><pre>
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.3", GitCommit:"b3cbbae08ec52a7fc73d334838e18d17e851274
9", GitTreeState:"clean", BuildDate:"2019-11-14T04:24:34Z", GoVersion:"go1.12.13", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.2", GitCommit:"c97fe5036ef3df2967d086711e6c0c405941e14
b", GitTreeState:"clean", BuildDate:"2019-10-15T19:09:08Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
</pre></details>

**What did you do?**

I executed first three steps from [hello-world-yaml example](https://github.com/KohlsTechnology/eunomia/tree/master/examples/hello-world-yaml#example) with the difference that I used `eunomia-demo` namespace instead of `eunomia-hello-world-yaml-demo` to avoid #202 and `eunomia-base:dev` image built locally from dev code.

**What did you expect to see?**

Running hello-world pod and one completed job.

**What did you see instead?**

New job being created each 10 seconds
<details><summary><code>kubectl get all -n eunomia-demo</code></summary><br><pre>
$ kubectl get all -n eunomia-demo
NAME                                             READY   STATUS      RESTARTS   AGE
pod/gitopsconfig-hello-world-yaml-04x10r-5k6wr   0/1     Completed   0          5m20s
pod/gitopsconfig-hello-world-yaml-69vjdi-jzqf9   0/1     Completed   0          4m20s
pod/gitopsconfig-hello-world-yaml-6zpv36-kf477   0/1     Completed   0          4m30s
pod/gitopsconfig-hello-world-yaml-75mfya-std2s   0/1     Completed   0          5m40s
pod/gitopsconfig-hello-world-yaml-7eja41-rwrqw   0/1     Completed   0          3m10s
pod/gitopsconfig-hello-world-yaml-7s340h-6vhlx   0/1     Completed   0          50s
pod/gitopsconfig-hello-world-yaml-9jdrwg-5jxwx   0/1     Completed   0          3m20s
pod/gitopsconfig-hello-world-yaml-9qa4e1-vs8h9   0/1     Completed   0          10s
pod/gitopsconfig-hello-world-yaml-clw34d-qp6f7   0/1     Completed   0          2m40s
pod/gitopsconfig-hello-world-yaml-fissi7-9dm2p   0/1     Completed   0          3m
pod/gitopsconfig-hello-world-yaml-hrkh5v-j6tb6   0/1     Completed   0          2m30s
pod/gitopsconfig-hello-world-yaml-i09cko-b89m6   0/1     Completed   0          80s
pod/gitopsconfig-hello-world-yaml-imlfms-mm4lp   0/1     Completed   0          4m40s
pod/gitopsconfig-hello-world-yaml-kf552t-wrtfm   0/1     Completed   0          60s
pod/gitopsconfig-hello-world-yaml-kpmruq-csfqb   0/1     Completed   0          5m50s
pod/gitopsconfig-hello-world-yaml-kx94re-96dxg   0/1     Completed   0          3m30s
pod/gitopsconfig-hello-world-yaml-liqmzj-ksjsk   0/1     Completed   0          40s
pod/gitopsconfig-hello-world-yaml-llzrsy-kt7mz   0/1     Completed   0          2m10s
pod/gitopsconfig-hello-world-yaml-m22s9s-gq4n8   0/1     Completed   0          2m
pod/gitopsconfig-hello-world-yaml-m5phj7-6hdhb   0/1     Completed   0          4m50s
pod/gitopsconfig-hello-world-yaml-o4443h-9thz6   0/1     Completed   0          70s
pod/gitopsconfig-hello-world-yaml-qbeerd-x79cc   0/1     Completed   0          2m50s
pod/gitopsconfig-hello-world-yaml-qd5b5l-555gk   0/1     Completed   0          30s
pod/gitopsconfig-hello-world-yaml-rogso3-dtwcj   0/1     Completed   0          20s
pod/gitopsconfig-hello-world-yaml-trfsg3-v7wn9   0/1     Completed   0          100s
pod/gitopsconfig-hello-world-yaml-ulnes0-6qvx4   0/1     Completed   0          5m
pod/gitopsconfig-hello-world-yaml-v1o3kj-84ld5   0/1     Completed   0          4m
pod/gitopsconfig-hello-world-yaml-vi4z4y-nczzk   0/1     Completed   0          5m30s
pod/gitopsconfig-hello-world-yaml-w5z0fc-f7g7d   0/1     Completed   0          3m40s
pod/gitopsconfig-hello-world-yaml-wex0pr-x9ct8   0/1     Completed   0          6m
pod/gitopsconfig-hello-world-yaml-wj751g-gbcqk   0/1     Completed   0          2m20s
pod/gitopsconfig-hello-world-yaml-wsrlhi-55qjx   0/1     Completed   0          90s
pod/gitopsconfig-hello-world-yaml-xhs1c2-q5qcw   0/1     Completed   0          5m10s
pod/gitopsconfig-hello-world-yaml-xkp83o-p2rjx   0/1     Completed   0          3m50s
pod/gitopsconfig-hello-world-yaml-zbv0s1-fpf5b   0/1     Completed   0          4m10s
pod/gitopsconfig-hello-world-yaml-zln4m5-62dlh   0/1     Completed   0          110s
pod/hello-world-7b7f58765c-6jk9j                 1/1     Running     0          5m55s

NAME                  TYPE       CLUSTER-IP    EXTERNAL-IP   PORT(S)          AGE
service/hello-world   NodePort   10.99.24.34   <none>        8080:30993/TCP   5m55s

NAME                          READY   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/hello-world   1/1     1            1           5m55s

NAME                                     DESIRED   CURRENT   READY   AGE
replicaset.apps/hello-world-7b7f58765c   1         1         1       5m55s

NAME                                             COMPLETIONS   DURATION   AGE
job.batch/gitopsconfig-hello-world-yaml-04x10r   1/1           6s         5m20s
job.batch/gitopsconfig-hello-world-yaml-69vjdi   1/1           6s         4m20s
job.batch/gitopsconfig-hello-world-yaml-6zpv36   1/1           6s         4m30s
job.batch/gitopsconfig-hello-world-yaml-75mfya   1/1           7s         5m40s
job.batch/gitopsconfig-hello-world-yaml-7eja41   1/1           7s         3m10s
job.batch/gitopsconfig-hello-world-yaml-7s340h   1/1           6s         50s
job.batch/gitopsconfig-hello-world-yaml-9jdrwg   1/1           6s         3m20s
job.batch/gitopsconfig-hello-world-yaml-9qa4e1   1/1           7s         10s
job.batch/gitopsconfig-hello-world-yaml-clw34d   1/1           6s         2m40s
job.batch/gitopsconfig-hello-world-yaml-fissi7   1/1           7s         3m
job.batch/gitopsconfig-hello-world-yaml-hrkh5v   1/1           7s         2m30s
job.batch/gitopsconfig-hello-world-yaml-i09cko   1/1           6s         80s
job.batch/gitopsconfig-hello-world-yaml-imlfms   1/1           7s         4m40s
job.batch/gitopsconfig-hello-world-yaml-kf552t   1/1           6s         60s
job.batch/gitopsconfig-hello-world-yaml-kpmruq   1/1           6s         5m50s
job.batch/gitopsconfig-hello-world-yaml-kx94re   1/1           6s         3m30s
job.batch/gitopsconfig-hello-world-yaml-liqmzj   1/1           7s         40s
job.batch/gitopsconfig-hello-world-yaml-llzrsy   1/1           6s         2m10s
job.batch/gitopsconfig-hello-world-yaml-m22s9s   1/1           6s         2m
job.batch/gitopsconfig-hello-world-yaml-m5phj7   1/1           7s         4m50s
job.batch/gitopsconfig-hello-world-yaml-o4443h   1/1           7s         70s
job.batch/gitopsconfig-hello-world-yaml-qbeerd   1/1           6s         2m50s
job.batch/gitopsconfig-hello-world-yaml-qd5b5l   1/1           7s         30s
job.batch/gitopsconfig-hello-world-yaml-rogso3   1/1           7s         20s
job.batch/gitopsconfig-hello-world-yaml-trfsg3   1/1           7s         100s
job.batch/gitopsconfig-hello-world-yaml-ulnes0   1/1           7s         5m
job.batch/gitopsconfig-hello-world-yaml-v1o3kj   1/1           7s         4m
job.batch/gitopsconfig-hello-world-yaml-vi4z4y   1/1           6s         5m30s
job.batch/gitopsconfig-hello-world-yaml-w5z0fc   1/1           7s         3m40s
job.batch/gitopsconfig-hello-world-yaml-wex0pr   1/1           12s        6m
job.batch/gitopsconfig-hello-world-yaml-wj751g   1/1           7s         2m20s
job.batch/gitopsconfig-hello-world-yaml-wsrlhi   1/1           7s         90s
job.batch/gitopsconfig-hello-world-yaml-xhs1c2   1/1           6s         5m10s
job.batch/gitopsconfig-hello-world-yaml-xkp83o   1/1           7s         3m50s
job.batch/gitopsconfig-hello-world-yaml-zbv0s1   1/1           6s         4m10s
job.batch/gitopsconfig-hello-world-yaml-zln4m5   1/1           7s         110s
</pre></details>

which is strange because trigger is of type "Change".

**Comment by sbar95** [comment]
The regularity is strange - there is no chance that the webhook has been somehow set to "Periodic". It looks as if one job was triggering the next one and so on, but I might be wrong - it's just my educated guess.

**Comment by seanmalloy** [comment]
@sbar95 I believe this bug was introduced in #163

**Comment by sbar95** [comment]
@seanmalloy Thanks for the info, I'm trying to debug and repair it to make #52 reproducible - then I'll get down to it again.

**Comment by akavel** [comment]
@sbar95 if you're working on it, try if maybe using GenerationChangePredicate would help — I read about it recently in: https://blog.openshift.com/kubernetes-operators-best-practices/. I'm not sure if that's it, but I guess worth a try...

**Comment by sbar95** [comment]
@seanmalloy 
So far:
[The Update() function](https://github.com/KohlsTechnology/eunomia/blob/v0.0.5/pkg/controller/gitopsconfig/jobmonitor.go#L239) from jobmonitor.go, whenever called, always causes a **new reconcile cycle** to be started. It's because the function updates GitOpsConfig - and this triggers a new reconciliation loop.

1. In the new reconciliation loop [a new job is created and is being watched for status](https://github.com/KohlsTechnology/eunomia/blob/v0.0.5/pkg/controller/gitopsconfig/controller.go#L194-L199).
2. The [watchJobForStatus](https://github.com/KohlsTechnology/eunomia/blob/v0.0.5/pkg/controller/gitopsconfig/jobmonitor.go#L128) function calls [watchjob](https://github.com/KohlsTechnology/eunomia/blob/v0.0.5/pkg/controller/gitopsconfig/jobmonitor.go#L143) function.
3. Which in turn sooner or later calls [updateStatus](https://github.com/KohlsTechnology/eunomia/blob/v0.0.5/pkg/controller/gitopsconfig/jobmonitor.go#L229) function.
4. Where [the Update() function](https://github.com/KohlsTechnology/eunomia/blob/v0.0.5/pkg/controller/gitopsconfig/jobmonitor.go#L239) is executed so a new reconcile cycle is started (goto point 1.)

Looks like a vicious circle :/

Now when I know what's the problem I'm trying to come up with a solution to it.
The real problem is that the Update function cannot be called - because it has the effect of updating the GitOpsConfig which causes a new reconcile cycle to be started (because there is "Change" trigger in the GitOpsConfig).

So,
either the function has to be sanitized in such a way that it won't start a new reconciliation loop (as for now I don't know how to do it or if it's even possible - I'm rather new to this)
or adding the status section to GitOpsConfig has to be done in some different way (but in the end it's always **updating the GitOpsConfig** which by definition causes a new reconcile cycle to be started while using the "Change" trigger).

First I need to understand the logic and all possible usecases in [jobmonitor.go](https://github.com/KohlsTechnology/eunomia/blob/v0.0.5/pkg/controller/gitopsconfig/jobmonitor.go) thoroughly. For now I've just found the reason behind the issue and understand jobmonitor.go only partly. Maybe I'll come up with something. I'm also going to look into the article @akavel linked.

**Comment by seanmalloy** [comment]
@sbar95 thanks for the update!

**Comment by sbar95** [comment]
Thanks @akavel for the article! It was _exactly_ what I needed.
