### ISSUE TITLE
Add kubernetes readiness check uri

### ISSUE THREAD

**Issue by vinny-sabatini** [KohlsTechnology/eunomia#210]
**Is your feature request related to a problem? Please describe.**

In a Kubernetes deployment, it is recommended to include a readiness check for your application to let Kubernetes know when your pods are ready to accept traffic. A readiness endpoint should be created for the Eunomia operator, and it should be included in the Eunomia deployment.

**Describe the solution you'd like**

A `/readiness` endpoint is created that returns `200` when the operator is able to access the Kubernetes API. This should be included in the deployment of Eunomia.

**Describe alternatives you've considered**

It may be possible to add this into the operator-sdk itself. It looks like there is an issue that may include a Liveness and Readiness probe.
I'm not exactly sure how it would work if it were included in the operator-sdk in the case that an end user wants to have a different check/include additional checks. I would assume it would need to be extendable/configurable for the different operator use cases.

**What version of eunomia are you using?**

eunomia version: v0.0.5

**Additional context**

- Issue #248  has been created to add the health/Liveness endpoint to Eunomia
- Here is the issue in the operator-sdk repo - https://github.com/operator-framework/operator-sdk/issues/1234

**Comment by akavel** [comment]
1. How are the semantics of this endpoint expected to differ vs. the one from #180? Typically I'd expect one endpoint to be a dumb "always return HTTP 200", and a second one checking if the app can do anything reasonable (so, checking if we can contact Kubernetes API?) Now, both this issue (#210) and #180 seem to mention some detailed checks, so I'm not sure how exactly we want them to differ.
  2. Do you know by chance if there's some specific Kubernetes API we could reasonably use for the check? Or do we want to leave it to be researched by the implementor? (sounds reasonable to me, just asking if you maybe happen to know some cool one off the top of your head)

**Comment by vinny-sabatini** [comment]
For 1, great call out, I'm checking in the other issue to see which issue should create the readiness check and which issue should create the health check so we don't have duplicate issues.
For 2, maybe we have it try to get the `gitopsconfigs.eunomia.kohls.io` in the namespace?

**Comment by akavel** [comment]
@vinny-sabatini by "get the `gitopsconfigs..." you mean basically `kubectl get gitopsconfigs...`, did I understand this correctly? sounds a good idea to me, thanks!

**Comment by vinny-sabatini** [comment]
Yes, a `kubectl get gitopsconfigs.eunomia.kohls.io` was what I had in mind

**Comment by sanbornick** [comment]
Does it make sense to follow the z-pages pattern for this endpoint @vinny-sabatini @seanmalloy? If so endpoint should be `/readinessz`then.

**Comment by sanbornick** [comment]
#180 is about specific GCP LB use cases. Instead I've created a new issue to track just the health endpoint and we can leave #180 out there to track this GCP LB use case. I've updated the issues main description with the new related issue.

**Comment by sanbornick** [comment]
Additionally, this could check the connectivity to the scm but that may get complicated quickly and could be its own issue.

**Comment by seanmalloy** [comment]
I good with `/readinessz` or `/readyz`
