### ISSUE TITLE
Refactor GitOpsConfig Status Update Code

### ISSUE THREAD

**Issue by seanmalloy** [KohlsTechnology/eunomia#217]
**Is your feature request related to a problem? Please describe.**

No, this is a code refactoring enhancement.

**Describe the solution you'd like**

I would like the code(`pkg/controller/gitopsconfig/jobmonitor.go`) that updates the `.status` section of the GitOpsConfig CR to use the same approach(k8s Informers) as Event creation.

**Describe alternatives you've considered**

The current code that updates the `.status` section is not as reliable as we would like.

**What version of eunomia are you using?**

eunomia version: v0.0.5

**Additional context**

We believe using k8s Informers for updating the `.status` section will be more robust than than current approach. See PR #212.

**Comment by akavel** [comment]
When completing this work, please remove the [relevant TODO in jobmonitor.go](https://github.com/KohlsTechnology/eunomia/blob/525d288c85377b4a84a9011696a78276ba50b9e8/pkg/controller/gitopsconfig/jobmonitor.go#L33).

Also related: #179.

**Comment by seanmalloy** [comment]
I'm closing this for now. We can improve the code that updates the `.status` section in the future. For now I believe it is working much better than before. Closed by #249.
