### ISSUE TITLE
RFC: Split template-processor into separate images, for easier templating

### ISSUE THREAD

**Issue by akavel** [KohlsTechnology/eunomia#221]
## Is your feature request related to a problem? Please describe.

This was originally triggered by mainly two things:

-   being super frustrated by long rebuilds of template-processor images whenever I need to change something in the "base" template-processor image (like gitPull.sh, resourceManager.sh, etc.) — i.e. long development feedback loop, before I was able to test if any change works.
    
-   feeling very uneasy that template-processor images must include stuff from eunomia-base that is completely irrelevant to actual *template processing* (like git, etc.) — also resulting in issues like #159. Basically in my mind it should be possible for template-processor to be just a simple image taking 2 inputs (templates + params) and emitting 1 output (rendered templates).
    

## Describe the solution you'd like

I'd like to propose splitting the base template processor image into 2-3 images, for separate phases/layers of the data flow. As an "excutive summary", I'd like to propose to structure them in such a way, that "**users could write one-liner template processor images**". Rough implementation sketch that I have in mind:

***Image 1: VCS*** == `gitPull.sh`

-   must put the results in `/git/templates/` and `/git/parameters/`, as before
-   eunomia saves the results into a ConfigMap
    

***Image 2: MANAGER, subcommand DISCOVER*** == `discoverEnvironment.sh` + pulling "facts" from the target live k8s cluster

-   must put the results... where? in env? in some files somewhere?
-   eunomia saves the results into another ConfigMap?
    

***Image 3: process parameters?***

-   ... envsubst?
    

***Image 4: TEMPLATE*** == `processTemplates.sh` (+ `processParameters.sh`?)

-   input is provided by eunomia from ConfigMap saved after image 1 +
-   basically, as is
-   ***can emit a "don't apply" value, so that next phase won't be run***
    

***Image 2: MANAGER, subcommand APPLY*** == `resourceManager.sh`

----

### Benefits

-   writing template processors becomes relatively trivial to users, assuming they already know docker (arguably it's already fairly easy, "just override processTemplates.sh"; but then, they wouldn't even have to do this, just write usual ENTRYPOINT)
    
    -   we could potentially maybe even *just use some "vanilla" generic images* from docker hub/quay, if they allow customizing the input & params & output directories through env variables / mount points
        
-   we get well defined protocol between various phases of the data flow
    
-   users can pull any dependencies they like (we should hopefully no longer need to care about stuff like #159)
    
-   users' images can use any base image they like, don't have to be based on RedHat UBI (can use the usual Alpine Linux base, or Ubuntu, or whatever)
    
    -   as an added benefit, we offload security concerns & control in that area to users
        
-   users' images become hugely independent of the version of eunomia they work with (barring some major changes in the input/output dirs protocol)
    
-   users don't have to rebuild images from scratch with each new version of eunomia we release
    
    -   which also means our tests will run faster in some cases: when changing the scripts (like gitPull.sh), only 1 image will be rebuilt, instead of 4 ones as is now
        
-   we could make it possible to use version control systems different than git, and make it easy for users to mix and match git/mercurial/svn/clearcase/... + ansible/jinja/...
    
-   we could cache the results of intermediate steps in the cluster — for example, when pulling from github, if the commit SHA didn't change, we wouldn't have to re-run gitPull.sh, and could just run template-processor (reusing cached git commit contents), or maybe even only resourceManager.sh (reusing cached template-processor results — though this won't make much sense once we introduce environment discovery features)
    
-   we should be able to relatively easily support various versions of e.g. kubectl (#220), for any template-processor
    

### Disadvantages / concerns / open issues

-   we'd have to use more Docker images & k8s Pods, and this:
    - increases complexity — though arguably, current approach is also complex just in a different way (by template processors having to copy the base image)
    - increases resources usage — though maybe a couple more Pods is not a big concern in kubernetes world?
- not really sure where to put processParameters in this model :/
    

## Describe alternatives you've considered

-   Also considered implementing the split as a single Job composed of several Pods, and sharing data through volumes instead of ConfigMaps. However, this wouldn't allow for caching between "phases/layers".
    

## Additional context

I'm submitting this as a Request For Comments, to hopefully get feedback and discussion if you think it's a good or bad idea, or if you have some ideas how to improve this. I'm myself not yet 100% convinced, but I kinda feel more and more aspects "clicking into place" with this approach (e.g. the newly opened issue #220 would seem super easy to solve with this approach to me).

**What version of eunomia are you using?**

eunomia version: v0.0.6

**Comment by Smiley73** [comment]
There are security concerns with leveraging a config map, because you more than likely will end up having secrets in your yaml files. That's a no-go. Config maps also have a size limitation and would need to reflect the name of the gitopsconfig CR (because we could have multiple in the same namespace).
Would it be better to have a pod defined with a shared storage between the containers?
I like the ability to e.g. have different kubectl image version. It'll make supporting this rather easy.
We'd also have to determine how we could easily 'attach' additional features into the chain, like adding a custom secrets backend.

**Comment by akavel** [comment]
Personally, I think this idea should also work ok with any other kind of intermediate storage, so a Pod with shared storage hopefully would be ok? Here I must admit I just plain don't know Kubernetes well enough to know even what are the possibilities. That's absolutely an important part of the reason why I wanted to solicit some thoughts and opinions from you guys on this!

One thing as to a pod with shared storage, is that I was told there may be some challenges with node affinity in such case; but I may have misunderstood as well — as I say, this kind of Kubernetes stuff is currently way over my head, unfortunately :/ The concern about security is I think totally a valid one.

One thing I'd like to say is that I'm not really set on any particular implementation. To me personally, the thing that feels most important, and kinda the most distilled minimal idea here, at least for starters, would be to let users plug in/write "one-liner template processor docker images", with no requirement of depending on eunomia's base image. I'm personally very open to any and all ideas how in particular this could be implemented. If you can come up with something simpler, I'd be stoked!

**Comment by Smiley73** [comment]
Take a look at this: https://kubernetes.io/docs/tasks/configure-pod-container/configure-pod-initialization/#create-a-pod-that-has-an-init-container

**Comment by seanmalloy** [comment]
I've linked this to the v1alpha2 proposal #183

**Comment by akavel** [comment]
@Smiley73 do you know if there's a way to order more than 2 containers with this mechanism? I think we'd want at least 3 of them, if not more, in a sequence...? I believe @mkyc once suggested an arrangement to make each container in a Pod wait until the previous one is finished, based on some signalling through files or sockets, IIUC. I kinda also pondered if some third-party k8s operators introducing a concept of "[data] flow" could be maybe used here; though that feels a bit too heavyweight to me, at least at a first glance...

**Comment by Smiley73** [comment]
@akavel as discussed on our call, init containers get executed in order. One first has to successfully complete, before it starts the next one. I believe this gives you what you're looking for.

**Comment by akavel** [comment]
@Smiley73 Thanks! From the first link I somehow grew an impression that there can be only one init container, and didn't go on to read the next link. Which then proceeds to explain how those seem to be a good fit for trying to build this flow on indeed :)
