### ISSUE TITLE
Deleting GitOps CR can get into endless loop

### ISSUE THREAD

**Issue by tomsucho** [KohlsTechnology/eunomia#238]
**What version of eunomia are you using?**

eunomia version:
v0.0.4
**Does this issue reproduce with the latest release?**
not tested yet

**What operating system and processor architecture are you using (`kubectl version`)?**

<details><summary><code>kubectl version</code> Output</summary><br><pre>
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.8", GitCommit:"211047e9a1922595eaa3a1127ed365e9299a6c23", GitTreeState:"clean", BuildDate:"2019-10-15T12:11:03Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.8-gke.12", GitCommit:"188432a69210ca32cafded81b4dd1c063720cac0", GitTreeState:"clean", BuildDate:"2019-11-07T19:27:01Z", GoVersion:"go1.12.11b4", Compiler:"gc", Platform:"linux/amd64"}
</pre></details>

**What did you do?**
deleted a GitOps CR which triggered job/pod with ACTION=DELETE, however due to connectivity issues the POD was not able to clone related Git repo and hence the POD exited with error status. It retried 5 times and finally backedOffLimitedExceeded kicked in, however the related kubectl delete CR command hung forever:

```
$ kubectl delete gitopsconfig gitops-gcp-kohls-dev-cne-demo2-lle -n gcp-kohls-dev-cne-demo2-lle
gitopsconfig.eunomia.kohls.io "gitops-gcp-kohls-dev-cne-demo2-lle" deleted


```
and the logs of operator show repeatedly the following:

```
{"level":"info","ts":1578671192.4506927,"logger":"controller_gitopsconfig","msg":"Reconciling GitOpsConfig","Request.Namespace":"gcp-kohls-dev-cne-demo2-lle","Request.Name":"gitops-gcp-kohls-dev-cne-demo2-lle"}
{"level":"info","ts":1578671192.4507565,"logger":"controller_gitopsconfig","msg":"found instance","Request.Namespace":"gcp-kohls-dev-cne-demo2-lle","Request.Name":"gitops-gcp-kohls-dev-cne-demo2-lle","instance":"gitops-gcp-kohls-dev-cne-demo2-lle"}
{"level":"info","ts":1578671192.4507673,"logger":"controller_gitopsconfig","msg":"Instance is being deleted","instance":"gitops-gcp-kohls-dev-cne-demo2-lle"}

```

**What did you expect to see?**
kubectl delete CR should not hang 

**What did you see instead?**
kubectl delete CR has hung forever

**Comment by akavel** [comment]
Whew, good that we added "eunomia version" in the bug report template, and big thanks to you for filling this value in! This helped me see you're reporting it for an old version of eunomia, and this bug is actually expected to be already fixed since eunomia 0.1.0 (https://github.com/KohlsTechnology/eunomia/commit/d5c1156bd1601fb9d2a58aba7f6fc3ef67ecfbb2).

As such, I'm closing this for now. If you however notice this occurring in eunomia 0.1.0+, please nag us here to reopen! Thanks
