### ISSUE TITLE
Handle Delete After Push

### ISSUE THREAD

**Issue by seanmalloy** [KohlsTechnology/eunomia#24]
## What happens?

Removing a yaml file from my git repo does not delete the corresponding k8s object(deployment, service, etc) from my cluster. The object just becomes unmanaged.

## What were you expecting to happen?

After deleting a k8s yaml file from a git repo. I would like this operator to remove that corresponding k8s object(deployment, service, etc) from my cluster.

## Steps to reproduce: 

n/a

## Any errors, stacktrace, logs? 

no

## Environment:

* Runtime version(Java, Go, Python, etc): n/a
* Desktop OS/version: n/a

## Additional comments:

@raffaelespazzoli has some ideas on how to implement this.

**Comment by raffaelespazzoli** [comment]
@seanmalloy I'm answering here. 
The way I solve this problem in the namespace-configuration-operator is the following:
1. all created objects are labeled with a marker that allows to recognize to which gitopsconfig they belong.
2. using the discovery client one can find all the defined resource type
3. for each resource type use the dynamic client to see if there are instances with a given label
4 execute a left outer join between the result of 3 and the current set of object requested by gitopsconfig.
5 delete the objects resulting at 4

this can probably be scripted in bash, but it would probably be ugly. So you might want to consider writing this piece with a small go utility.
For example this one: https://github.com/yanc0/untrak is pretty close to what you need.
