### ISSUE TITLE
RBAC Roles Issue

### ISSUE THREAD

**Issue by MeganMoran** [KohlsTechnology/eunomia#240]
**What version of eunomia are you using?**

eunomia version: v0.1.0

**Does this issue reproduce with the latest release?**
Yes

**What operating system and processor architecture are you using (`kubectl version`)?**

<details><summary><code>openshift version</code> Output</summary><br><pre>
$ openshift version 
OpenShift Master:
v3.11.98
Kubernetes Master:
v1.11.0+d4cacc0
OpenShift Web Console:
v3.11.98

</pre></details>

**What did you do?**

oc apply -f eunomia-test.yaml (ping Megan Kroll at Kohl's for repo)

**What did you expect to see?**
No errors in logs

**What did you see instead?**
A ton of RBAC policy errors, see attached logs

[gitopsconfig-eunomia-test.log](https://github.com/KohlsTechnology/eunomia/files/4048261/gitopsconfig-eunomia-test.log)

**Comment by seanmalloy** [comment]
@MeganMoran thanks for the bug report!

I noticed the same problem when doing some testing recently on OpenShift 3.11 too. I've added this to the `near-term` milestone for now.
