### ISSUE TITLE
Add kubernetes liveliness(health) check uri

### ISSUE THREAD

**Issue by sanbornick** [KohlsTechnology/eunomia#248]
**Is your feature request related to a problem? Please describe.**
In a Kubernetes deployment, it is recommended to include a liveliness check for your application to let Kubernetes know when your pods are healthy or need to be rebooted. A readiness endpoint should be created for the Eunomia operator, and it should be included in the Eunomia deployment.

**Describe the solution you'd like**
An endpoint at either `/healthz` or `/livelinessz` is created that returns 200 always. This should be included in the deployment of Eunomia.

**Describe alternatives you've considered**
Same as described in #210 

**Additional context**
Readiness probe is covered by #210

**Comment by akavel** [comment]
Please fix word "readiness" in sentence 2 in paragraph 1 to some appropriate one, to try and remove any chance of confusion with #210.

**Comment by seanmalloy** [comment]
Yeah ... I think there is a difference between #180  and #210, but I can't exactly remember now.
