### ISSUE TITLE
Add To operatorhub.io

### ISSUE THREAD

**Issue by seanmalloy** [KohlsTechnology/eunomia#26]
## What happens?

This operator is not available on operatorhub.io

## What were you expecting to happen?

I want to see this operator on operatorhub.io

## Steps to reproduce: 

Open https://operatorhub.io/

## Any errors, stacktrace, logs? 

n/a

## Environment:

* Runtime version(Java, Go, Python, etc): na
* Desktop OS/version: na

## Additional comments:

none

**Comment by seanmalloy** [comment]
Work in progress pull request #86

**Comment by rajneesh-ops** [comment]
Closing this PR.Created a new one 
https://github.com/KohlsTechnology/eunomia/pull/235

**Comment by seanmalloy** [comment]
Closed by #235
