### ISSUE TITLE
Expose Eunomia Version Information To End User

### ISSUE THREAD

**Issue by seanmalloy** [KohlsTechnology/eunomia#260]
**Is your feature request related to a problem? Please describe.**

It is currently not possible to discover which version of eunomia is running other than by looking at the container image tag that is deployed.

**Describe the solution you'd like**

I would like the variables in `version/version.go` exposed to end users using prometheus metrics and a CLI option.

**Describe alternatives you've considered**

Being confused about which version of the eunomia operator is running.

**What version of eunomia are you using?**

eunomia version: v0.1.1

**Additional context**

None.

**Comment by akavel** [comment]
I think it would be great if we could then add an instruction guiding users how to do this into proper places in our [issue templates](https://github.com/KohlsTechnology/eunomia/tree/master/.github/ISSUE_TEMPLATE)

**Comment by vinny-sabatini** [comment]
> I think it would be great if we could then add an instruction guiding users how to do this into proper places in our [issue templates](https://github.com/KohlsTechnology/eunomia/tree/master/.github/ISSUE_TEMPLATE)

This is in reference to the `What version of eunomia are you using?` block of the issue template, having the exact command the end user should use to retrieve this. For example `/usr/local/bin/eunomia-operator --version`.

**Comment by akavel** [comment]
> the exact command the end user should use to retrieve this

Ideally, it would be best if this could retrieve version from cluster - so my thoughts are to maybe use one of:
 - something like `kubectl exec $EUNOMIA_POD /usr/local/bin/eunomia-operator --version` ?
 - or somehow a command that would scrape a corresponding Prometheus metric from the eunomia Pod ?
 - or we could print this into eunomia Pod logs and tell user how to grep it from the Pod logs?

I mean sometimes accidentally the version on cluster might be different than the version someone has on their laptop, and then it would be really useful if we could make sure we really have correct version from the cluster...
