### ISSUE TITLE
tests in pkg/controller/gitopsconfig/controler_test.go have serious problems

### ISSUE THREAD

**Issue by akavel** [KohlsTechnology/eunomia#264]
**What version of eunomia are you using?**

eunomia version: 0.1.1

**Does this issue reproduce with the latest release?**

yes

**What operating system and processor architecture are you using (`kubectl version`)?**

N/A

**What did you do?**

I looked into [pkg/controller/gitopsconfig/controller_test.go]( https://github.com/KohlsTechnology/eunomia/blob/1345a37fed68aefe42e01f1ecebc92d58304526d/pkg/controller/gitopsconfig/controller_test.go )

**What did you expect to see?**

Unit tests written in neat and clean way, in good Go style, with no glaring issues

**What did you see instead?**

Many issues of various troublesomeness,  some of them **very bad**, including:

 - **very bad**: [a single global object shared and]( https://github.com/KohlsTechnology/eunomia/blob/1345a37fed68aefe42e01f1ecebc92d58304526d/pkg/controller/gitopsconfig/controller_test.go#L311-L316 ) modified [between many tests]( https://github.com/KohlsTechnology/eunomia/blob/1345a37fed68aefe42e01f1ecebc92d58304526d/pkg/controller/gitopsconfig/controller_test.go#L142 )
 - **very bad**: [errors in tests being]( https://github.com/KohlsTechnology/eunomia/blob/1345a37fed68aefe42e01f1ecebc92d58304526d/pkg/controller/gitopsconfig/controller_test.go#L554)  logged [with log.Error]( https://github.com/KohlsTechnology/eunomia/blob/1345a37fed68aefe42e01f1ecebc92d58304526d/pkg/controller/gitopsconfig/controller_test.go#L436 )  instead of making test fail via t.Error/t.Errorf
 - dubious: [third-party assert package used instead of standard library builtin t.Error functionality]( https://github.com/KohlsTechnology/eunomia/blob/1345a37fed68aefe42e01f1ecebc92d58304526d/pkg/controller/gitopsconfig/controller_test.go#L459 )
 - also more of smaller-grade issues that would take too much time to describe here

With how the tests are built, it's entirely possible that some of them may be currently broken or failing but not showing this in CI. Also, they're giving a very bad example of how to write Go to anyone that might need to read this code and/or add their own tests into this file, thus being dangerous from teaching/mentoring point of view.

**Comment by seanmalloy** [comment]
@akavel I added this to the v0.1.3 milestone for now. It might slip to the v0.1.4 milestone which does not exist yet.

**Comment by seanmalloy** [comment]
Closed by #296
