### ISSUE TITLE
Improve clarity in README.md

### ISSUE THREAD

**Issue by vinny-sabatini** [KohlsTechnology/eunomia#289]
**Is your feature request related to a problem? Please describe.**

The Eunomia projects [README.md](https://github.com/KohlsTechnology/eunomia/blob/master/README.md) currently does not tell you what it does until it's fourth section, it is quite long, and it does not have a good flow/organization to it.

**Describe the solution you'd like**

- The README.md should explain to a user what Eunomia does at the very beginning.
- If there is an example usage included in the README, it should be short, and further detailed usage should be moved into different documents and referenced in the README where necessary.

**Describe alternatives you've considered**

The README could be left how it is.

**What version of eunomia are you using?**

eunomia version: v0.1.2

**Additional context**

**Comment by seanmalloy** [comment]
I added this to the near-term milestone for now. Also, I think going forward we should treat issues with the documentation as bugs, so I changed this from an enhancement to a bug.
