### ISSUE TITLE
Operator Hub is needs to be updated with new releases

### ISSUE THREAD

**Issue by Smiley73** [KohlsTechnology/eunomia#297]
**Is your feature request related to a problem? Please describe.**
Operatorhub.io has an outdated version of Eunomia. Newer versions are much more stable and should be used by anybody interested in the tool.

**Describe the solution you'd like**
Every sprint, as we release a new version, operator hub gets also updated.

**Comment by vinny-sabatini** [comment]
For reference, PR #294 got this part of the way there.

I believe the last piece would be to update the Makefile to properly run the script when a release is created.

**Comment by seanmalloy** [comment]
I also just submitted PR #300 to document some steps that were missing in the release process. I plan on pushing v0.1.3 to operatorhub.io.

**Comment by seanmalloy** [comment]
> I believe the last piece would be to update the Makefile to properly run the script when a release is created.

Running the script will be a manual process for now. We won't add this to the fully automated release steps right now.

**Comment by seanmalloy** [comment]
PR to update operatorhub.io to v0.1.4 ... https://github.com/operator-framework/community-operators/pull/1291. We will be doing this for every release now going forward.
