### ISSUE TITLE
CR Status Updater code should not check the jobs which are not owned by any CR

### ISSUE THREAD

**Issue by sharafcmr** [KohlsTechnology/eunomia#305]
****

<details><summary><code>oc logs -f eunomia-operator-xxxx | grep unstarted</code> Output</summary><br><pre>
800000"}
{"level":"info","ts":1582800001.6407642,"logger":"gitopsconfig-controller","msg":"unstarted Job found; cannot properly set GitOpsConfig.Status based on it, ignoring","job":"test-pod-cleanup-1582800000"}
{"level":"info","ts":1582800001.793193,"logger":"gitopsconfig-controller","msg":"unstarted Job found; cannot properly set GitOpsConfig.Status based on it, ignoring","job":"yyy-check-1582800000"}
{"level":"info","ts":1582800060.1646621,"logger":"gitopsconfig-controller","msg":"unstarted Job found; cannot properly set GitOpsConfig.Status based on it, ignoring","job":"xxxx-1582800060"}
{"level":"info","ts":1582800130.749391,"logger":"gitopsconfig-controller","msg":"unstarted Job found; cannot properly set GitOpsConfig.Status based on it, ignoring","job":"test-data--1582800120"}
</pre></details>

eunomia version: v0.1.3

**What operating system and processor architecture are you using (`oc version`)?**

<details><summary><code>oc version</code> Output</summary><br><pre>
$ oc version
oc v3.11.0+0cbc58b
kubernetes v1.11.0+d4cacc0
features: Basic-Auth

openshift v3.11.98
kubernetes v1.11.0+d4cacc0
</pre></details>

**What did you do?**

Operator log shows the below message quite frequently:
 
"msg":"unstarted Job found; cannot properly set GitOpsConfig.Status based on it" 

The status update code is spitting this error message for every jobs in the cluster that are not owned by any CR instance. It leads the operator log filling with lot of non-informative messages.

**What did you expect to see?**
CR status updater code should not check the status of jobs that are not owned by any CR and should not print the messages to log for those pods.

**What did you see instead?**

The status update code is spitting this error message for every jobs in the cluster that are not owned by any CR instance. It leads the operator log filling with lot of non-informative messages.

**Comment by seanmalloy** [comment]
@sharafcmr thanks for submitting this bug! I've added this to our `near-term` milestone for now. The soonest we will probably we able to get to this is April.

If someone wants to submit a PR to fix this that would be awesome.
