### ISSUE TITLE
gitopsconfig job not started after new CR has been created

### ISSUE THREAD

**Issue by Smiley73** [KohlsTechnology/eunomia#310]
**What version of eunomia are you using?**

<details><summary><code>kubectl exec $EUNOMIA_POD curl localhost:8383/metrics</code> Output</summary><br><pre>
eunomia_build_info{branch="HEAD",builddate="20200228-01:15:23",gitsha1="8a092cd1a977b9d66e37bf9a0a9c3c204d8e4bb7",goversion="go1.12.17",operatorsdk="v0.8.1",version="v0.1.4"}
</pre></details>

eunomia version: v0.1.4

**Does this issue reproduce with the latest release?**
Yes

**What operating system and processor architecture are you using (`kubectl version`)?**

<details><summary><code>kubectl version</code> Output</summary><br><pre>
Client Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.10-dispatcher", GitCommit:"f5757a1dee5a89cc5e29cd7159076648bf21a02b", GitTreeState:"clean", BuildDate:"2020-02-06T03:29:33Z", G
oVersion:"go1.12.12b4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.10-gke.17", GitCommit:"bdceba0734835c6cb1acbd1c447caf17d8613b44", GitTreeState:"clean", BuildDate:"2020-01-17T23:10:13Z", GoVer
sion:"go1.12.12b4", Compiler:"gc", Platform:"linux/amd64"}
</pre></details>

**What did you do?**
Installed Eunomia 0.1.4 on a new GKE cluster. 
Created a new GitOpsConfig.
The steps executed are in this script: https://github.com/Smiley73/google-next-2020-gitops-demo/blob/master/scripts/run_demo.sh

**What did you expect to see?**
The job pod gets started by the operator after the CR was created.

**What did you see instead?**
Nothing happens. Not events. No status updates in the CR.
`Annotations:  gitopsconfig.eunomia.kohls.io/initialized: true` is set in the CR.
Operator log messages:
```
{"level":"info","ts":1583190845.8262107,"logger":"gitopsconfig-controller","msg":"Reconciling GitOpsConfig","Request.Namespace":"next-gitops-demo","Request.Name":"google-config-connector"}
{"level":"info","ts":1583190845.8265254,"logger":"gitopsconfig-controller","msg":"found instance","Request.Namespace":"next-gitops-demo","Request.Name":"google-config-connector","instance":"google-config-connector"}
{"level":"info","ts":1583190845.8266091,"logger":"gitopsconfig-controller","msg":"Instance needs to be initialized","Request.Namespace":"next-gitops-demo","Request.Name":"google-config-connector","instance":"google-config-connector"}
```
After a restart of the operator pod it correctly starts the job.

**Comment by seanmalloy** [comment]
I believe I'm running into this issue on GKE too. Eunomia version v0.1.4.

```
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.1", GitCommit:"d224476cd0730baca2b6e357d144171ed74192d6", GitTreeState:"clean", BuildDate:"2020-01-14T21:04:32Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"15+", GitVersion:"v1.15.8-gke.3", GitCommit:"2ccf2c797713077f4a3d0f87c4b4bae725362326", GitTreeState:"clean", BuildDate:"2020-01-29T19:27:22Z", GoVersion:"go1.12.12b4", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by akavel** [comment]
@Smiley73 can you help me understand at which lines in the linked script does this bug happen? For someone debugging this, should they uncomment the commented-out lines here: https://github.com/Smiley73/google-next-2020-gitops-demo/blob/8632f1f27ee676dedfe3e9718a1a1dd2fc645f29/scripts/run_demo.sh#L35 ? A link to script in `master` branch as you did is tricky, as when you change the code of the relatively long script, I'm not quite sure where to look in it for the relevant commands. From your report above, this bug at quick glance looks potentially challenging to debug (given lack of information in logs), so the more you can help us understand how to reproduce, the easier it will be to narrow down the root cause and give you a fix faster. Also a permalink instead of `master` branch link can potentially make it easier to avoid miscommunication after the script is edited. Thanks!

**Comment by Smiley73** [comment]
@akavel 
This line https://github.com/Smiley73/google-next-2020-gitops-demo/blob/8632f1f27ee676dedfe3e9718a1a1dd2fc645f29/scripts/run_demo.sh#L21 is the initial gitopsconfig that gets applied and never executed. It's actually pretty simple, just create a new gitopsconfig on GKE and you'll hit the issue.
This is why we have the restart line in the demo right now: https://github.com/Smiley73/google-next-2020-gitops-demo/blob/8632f1f27ee676dedfe3e9718a1a1dd2fc645f29/scripts/run_demo.sh#L42

Simply use the `setup_gke.sh` script to spin up a test cluster for yourself to try it out. BUT PLEASE change the cluster name if you're working in the PaaS SBX project. We're using that for the demo preparation.
