### ISSUE TITLE
finalizer: possible race condition for Trigger=Periodic

### ISSUE THREAD

**Issue by akavel** [KohlsTechnology/eunomia#323]
**What version of eunomia are you using?**

<details><summary><code>kubectl exec $EUNOMIA_POD curl localhost:8383/metrics</code> Output</summary><br><pre>
$ kubectl get -n eunomia-operator endpoints/eunomia-operator -o jsonpath='{.subsets[*].addresses[*].targetRef.name}' | xargs -I% kubectl exec -n eunomia-operator % -- curl -sS localhost:8383/metrics | grep eunomia_build_info

</pre></details>

eunomia version: 0.1.5

**Does this issue reproduce with the latest release?**

Yes

**What operating system and processor architecture are you using (`kubectl version`)?**

<details><summary><code>kubectl version</code> Output</summary><br><pre>
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.8", GitCommit:"211047e9a1922595eaa3a1127ed365e9299a6c23", GitTreeState:"clean", BuildDate:"2019-10-15T12:11:03Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.2", GitCommit:"c97fe5036ef3df2967d086711e6c0c405941e14b", GitTreeState:"clean", BuildDate:"2019-10-15T19:09:08Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
</pre></details>

**What did you do?**

Delete a GitOpsConfig with `Trigger: "Periodic"`

**What did you expect to see?**

- CronJob removed
- all Jobs created by CronJob removed
- all resources managed by eunomia (GitOps) removed

**What did you see instead?**

- CronJob removed (implicitly, because its OwnerReference is set to GitOpsConfig)
- all Jobs created by CronJob removed
- resources managed by eunomia may not always get removed

In eunomia finalizer, because a CronJob is not deleted explicitly, there is a chance of a race condition. The finalizer creates `action=delete` Job, and before it ends, CronJob may create a new scheduled Job. As a result, managed resources deleted by `action=delete` Job may get re-created by the CronJob-originating Job, leading to improper/incomplete cleanup of managed resources.

**Comment by akavel** [comment]
To fix this, I propose to delete CronJob explicitly in finalizer, before creating `action=delete` Job.

However, it is important to avoid reintroducing issue #216. Ideally, I believe we would like to find a way to distinguish situations where:
 - a) managed resources were never properly created, because `.Spec.TemplateProcessor` URL was set incorrectly from the beginning 
    - --> in this case, an `action=delete` Job, if created, would also get stuck, therefore we should either not create it at all, or let it get stuck, but then remove finalizer after detecting the Job's `ErrImage` (or similar) status;
 - b) managed resources were properly created
    - --> in this case, we want to create an `action=delete` Job, and if it fails, we would like to clearly inform user that there's some problem and resources can't be cleaned up properly. In my opinion, we may want to not allow completely deleting GitOpsConfig then, so that user clearly sees there's some problem.
 
It is tricky how to handle those situations, because when we delete CronJob, all its child Jobs also get deleted, so it's difficult to determine if resources were ever created. Even before deleting CronJob, we can't be 100% sure about this just from analyzing Jobs statuses, as CronJob has option to delete old Jobs, so it could remove old statuses already (see #196).
 
My current proposal is as in the following steps, though I'm not 100% sure yet if it would work properly:
 1. Delete CronJob
 2. Delete all Jobs created by GitOpsConfig that are *NOT* `action=delete` Jobs
 3. Create an `action=delete` Job if it doesn't exist yet
 4. If `action=delete` Job exists and either succeeded, or is stuck in bad status (like `ErrImage` and similar, see: https://github.com/KohlsTechnology/eunomia/blob/a7590dc98da224ff4331cb5d8b10425f4e3432a6/pkg/controller/gitopsconfig/controller.go#L453), delete it *and* clean-up the finalizer from GitOpsConfig
 5. Otherwise, retry after a while (RetrySeconds)
 
This approach is not fully robust: it won't properly detect a situation where resources were created properly, but after some time, templateProcessor was changed by user, OR templateProcessor image was deleted from cluster and became inaccessible. However, I don't currently have a good idea how to detect such a situation without creating an extra helper ConfigMap object for extra state/history storage.

**Comment by sbar95** [comment]
Seems good to me - this approach, as you said, might not be fully robust in situations you described but in my opinion it's not that important that at some point everything had been working but then a wrong image has been provided - only current state counts, not what was before.

If user wants to delete GitOpsConfig, it means he also wants to delete all resources created (directly, or indirectly) by it - if a stuck job disallows the deletion of our CR, we should delete it, then the finalizer. I don't think that a stateful approach would be good here - the whole idea of CRs, and reconciliation is stateless after all.

There is also one thing that came across my mind - user sees that there is a stuck job because of a bad image, so he wants to upload a new GitOpsConfig with a proper image this time. We might allow it by checking if there is a stuck job while trying to create a new job in reconciliation loop - if the stuck job is there, we would just delete it to allow for new jobs creation (no need to delete anything else as stuck job couldn't've created anything).
