### ISSUE TITLE
New Helm v3 Template Processor

### ISSUE THREAD

**Issue by seanmalloy** [KohlsTechnology/eunomia#330]
**Is your feature request related to a problem? Please describe.**

No.

**Describe the solution you'd like**

I would like a helm v3 template processor. The current eunomia helm template processor uses helm v2.

**Describe alternatives you've considered**

Creating a eunomia helm v3 template processor that is not part of the main eunomia repo.

**What version of eunomia are you using?**

<details><summary><code>kubectl exec $EUNOMIA_POD curl localhost:8383/metrics</code> Output</summary><br><pre>
$ kubectl get -n eunomia-operator endpoints/eunomia-operator -o jsonpath='{.subsets[*].addresses[*].targetRef.name}' | xargs -I% kubectl exec -n eunomia-operator % -- curl -sS localhost:8383/metrics | grep eunomia_build_info

</pre></details>

eunomia version: v0.1.6

**Additional context**

N/A

**Comment by Smiley73** [comment]
My vote would be to upgrade the current one to helm 3. There's no reason to keep the old one around at this point...
