### ISSUE TITLE
Gitops Config managing itself creates race condition that will delete all resources

### ISSUE THREAD

**Issue by tavianot** [KohlsTechnology/eunomia#339]
**What version of eunomia are you using?**
0.1.6
<details><summary><code>kubectl exec $EUNOMIA_POD curl localhost:8383/metrics</code> Output</summary><br><pre>
$ kubectl get -n eunomia-operator endpoints/eunomia-operator -o jsonpath='{.subsets[*].addresses[*].targetRef.name}' | xargs -I% kubectl exec -n eunomia-operator % -- curl -sS localhost:8383/metrics | grep eunomia_build_info

</pre></details>

eunomia version:
0.1.6
**Does this issue reproduce with the latest release?**
yes

**What operating system and processor architecture are you using (`kubectl version`)?**
oc v3.11.0+0cbc58b
kubernetes v1.11.0+d4cacc0
Eunomia is running on an Openshift cluster
openshift v3.11.98
kubernetes v1.11.0+d4cacc0
<details><summary><code>kubectl version</code> Output</summary><br><pre>
$ kubectl version

</pre></details>

**What did you do?**
Created a GitOpsConfig resource that would manage itself as well as a deployment stateful set and services

applied a GitOpsConfig that templated out its own gitopsconfig yaml as well as other resources. 
The GitOpsConfig was set to trigger on webhook, cron, and change

**What did you expect to see?**
The gitops config would manage/update itself as well as other resources whenever an update was pushed to the branch.

**What did you see instead?**
The gitops config would fire multiple jobs and a race condition was created that could and did delete all of the resources as well as the GitopsConfig so then someone needed to reapply the GitOpsConfig.

**Proposed Ideas of what happened in eunomia**
the line that caused the deletion of all resources was https://github.com/KohlsTechnology/eunomia/blob/581ec8e6078b2f6a34a9ee2ae148cc808d954859/template-processors/base/bin/resourceManager.sh#L76
Since multiple jobs had kicked off for the same GitOpsConfig by one webhook and the GitOpsConfig was managing itself. I believe that one of the jobs updated the timestamps while the other job was running thus deleting the owned Kind of GitOpsConfig that had a different timestamp than it was expecting. So once the gitopsConfig was deleted then all of the other resources were deleted as well.

** Proposed Solutions **
multiple jobs for the same gitops config cannot run at the same time. 
Ensure the Gitops Config cannot manage itself

**Comment by sanbornick** [comment]
> Since multiple jobs had kicked off for the same GitOpsConfig by one webhook and the GitOpsConfig was managing itself. I believe that one of the jobs updated the timestamps while the other job was running thus deleting the owned Kind of GitOpsConfig that had a different timestamp than it was expecting.

The deletion logic does have problems when jobs overlap. We are mitigating this, in part at least, via #351 but we need a long term solution that can make the individual jobs idempotent or use a locking mechanism so that they are able to run concurrently if that case arises.

> So once the gitopsConfig was deleted then all of the other resources were deleted as well.

An option would be setting [resource deletion mode](https://github.com/KohlsTechnology/eunomia#resource-deletion-mode) to `None` which abandons resources managed by a `gitopsConfig` when that `gitopsConfig` is removed. Not ideal but its something...

**Comment by seanmalloy** [comment]
@sanbornick found a way to fix this ... https://github.com/kubernetes/community/blob/master/contributors/devel/sig-architecture/api-conventions.md#concurrency-control-and-consistency

**Comment by seanmalloy** [comment]
Fixed by #376.
