### ISSUE TITLE
Resource Deletion Incorrectly Triggered

### ISSUE THREAD

**Issue by seanmalloy** [KohlsTechnology/eunomia#351]
**What version of eunomia are you using?**

<details><summary><code>kubectl exec $EUNOMIA_POD curl localhost:8383/metrics</code> Output</summary><br><pre>
$ kubectl get -n eunomia-operator endpoints/eunomia-operator -o jsonpath='{.subsets[*].addresses[*].targetRef.name}' | xargs -I% kubectl exec -n eunomia-operator % -- curl -sS localhost:8383/metrics | grep eunomia_build_info

</pre></details>

eunomia version: v0.1.6

**Does this issue reproduce with the latest release?**
Yes

**What operating system and processor architecture are you using (`kubectl version`)?**

<details><summary><code>kubectl version</code> Output</summary><br><pre>
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.3", GitCommit:"2e7996e3e2712684bc73f0dec0200d64eec7fe40", GitTreeState:"clean", BuildDate:"2020-05-20T12:52:00Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.8-gke.15", GitCommit:"9cabee15e0922c3b36724de4866a98f6c2da5e6a", GitTreeState:"clean", BuildDate:"2020-05-01T21:47:04Z", GoVersion:"go1.13.8b4", Compiler:"gc", Platform:"linux/amd64"}
</pre></details>

**What did you do?**
Updated the parameters(yaml files) in my git repo. Specifically a block of yaml was commented out from one of the input parameter files this should have caused a single k8s resource to be removed from the target cluster. Instead a large number of k8s resources were deleted from the cluster that we did not expect to be deleted.

The single resource that should have been removed was a [GCP Config Connector ComputeFirewall](https://cloud.google.com/config-connector/docs/reference/resource-docs/compute/computefirewall). The additional resources that were removed were things like ComputeRouters, ComputeSubnetworks, ComputeSharedVPCHostProjects, and ComputeNetworks.

Note we are using a custom proprietary template processor that uses Ansible. This line of code that is provided from the base template processor image is what triggered the deletion: https://github.com/KohlsTechnology/eunomia/blob/988739ae96d923d1d9913ebeff54dabdae942058/template-processors/base/bin/resourceManager.sh#L96

**What did you expect to see?**
I expected a single k8s resource would be deleted from the cluster.

**What did you see instead?**
A large number of unexpected k8s resources were deleted from the cluster.

**Comment by vinny-sabatini** [comment]
I tested this using the same code base originally used to produce this bug. By simply commenting out a block of resources, the job only deleted the individual resource I was expecting it to delete, so the act of commenting out resources does not appear to be the root of the issue.

While testing, I did notice that for one of the `GitOpsConfig` objects, there was a point where there were multiple jobs running at the same time for that `GitOpsConfig`. I believe in the past there have been issues with race conditions where if you had multiple jobs running at the same time one job would delete the other job's resources, so my current theory is this is what caused the unexpected deletion.

**Comment by vinny-sabatini** [comment]
I looked into the Audit logs for our K8S cluster and found that there were two jobs created within 0.1 seconds of each other. 

The first job created by the service account `eunomia-operator` and had the `GitOpsConfig` as the owner reference, meaning Eunomia created the `Job`. The second job was created by the service account `kube-system:cronjob-controller` and had the `CronJob` as the owner reference, meaning for some reason the CronJob thought it had to create a job.

The puzzling part is that the Cron was scheduled to run at 8:00PM CDT, however the job was actually created at 11:15AM CDT, so something caused the CronJob to create a job off schedule. I am looking in the code to see if Eunomia is causing this to happen.

**Comment by Smiley73** [comment]
@vinny-sabatini we definitely have issues with more than one job getting kicked off. It happens most of the time when a new CR gets created. Not sure if those issues are intermixed. The one I caught in the e2e testing doesn't include a cron schedule I believe.
We have already code in the tests to test for this, but it's disable until we find the root cause. Maybe it'll help you with your work.
https://github.com/KohlsTechnology/eunomia/blob/a1c81ae053a2112ba7d3fee0b93b2aba3491e3e6/scripts/e2e-test.sh#L385

**Comment by vinny-sabatini** [comment]
Thanks for the tip @Smiley73 . I talked with @sanbornick and @seanmalloy this morning, and there is only so much we can do to try to prevent multiple Kubernetes jobs from running at the same time.

We may be spending too much time trying to manipulate the Job/CronJob creation logic and may want to change our focus to making Eunomia Jobs idempotent so we don't care if multiple jobs run at the same time. And we especially don't cause unexpected deletion because of multiple Jobs running at once.
