### ISSUE TITLE
Change Trigger to GitOpsconfig creates two Jobs and two pods

### ISSUE THREAD

**Issue by Beardface123** [KohlsTechnology/eunomia#365]
**What version of eunomia are you using?**

<details><summary><code>kubectl exec $EUNOMIA_POD curl localhost:8383/metrics</code> Output</summary><br><pre>
$ kubectl get -n eunomia-operator endpoints/eunomia-operator -o jsonpath='{.subsets[*].addresses[*].targetRef.name}' | xargs -I% kubectl exec -n eunomia-operator % -- curl -sS localhost:8383/metrics | grep eunomia_build_info

</pre></details>

eunomia version: v0.1.6

**Does this issue reproduce with the latest release?**
Unknown

**What operating system and processor architecture are you using (`kubectl version`)?**
platform: darwin/amd64

<details><summary><code>kubectl version</code> Output</summary><br><pre>
$ kubectl version

</pre></details>

**What did you do?**
Edited the gitopsconfig for the namespace
Updated the cron field to trigger the change trigger.  When the config was saved, kubectl returned that it had been edited.

**What did you expect to see?**
when use kubectl to get the pods, I expected to see a single running pod

**What did you see instead?**
I saw two pods created within a second of each other.

```
bectl get pods -n SOMENAME | grep Running
gitopsconfig-SOMENAME-1597284000-x4jth   1/1     Running   0          58s
gitopsconfig-SOMENAME-v49q0i-dws7g       1/1     Running   0          59s
```

```
kubectl get jobs -n somename
NAME                                                  COMPLETIONS   DURATION   AGE
gitopsconfig-SOMENAME-1597284000   1/1           2m57s      3m1s
gitopsconfig-SOMENAME-v49q0i       1/1           2m41s      3m2s
```

**Comment by seanmalloy** [comment]
@Beardface123 thanks for opening this bug. I've added it to the v0.1.8 milestone for now.

**Comment by vinny-sabatini** [comment]
Some more details for troubleshooting/debugging this issue:

I took a look into the GKE cluster in which this bug was discovered and found that the owner reference for `gitopsconfig-SOMENAME-1597284000` was a `CronJob` and the owner reference for `gitopsconfig-SOMENAME-v49q0i` was the `GitOpsConfig` resource.

**Comment by Smiley73** [comment]
We already got test cases prepared for this, they just need to be enabled:
https://github.com/KohlsTechnology/eunomia/blob/15fe78d794869b3d2585b7ba26bb2b7046ff4748/scripts/e2e-test.sh#L385
(You'll find it a couple more times).
