### ISSUE TITLE
Enable successfulJobsHistoryLimit and failedJobsHistoryLimit to Cronjob Template

### ISSUE THREAD

**Issue by vjayraghavan** [KohlsTechnology/eunomia#366]
**Is your feature request related to a problem? Please describe.*
We want to have the ability to delete pods and keep only few Successful/Failed pods.

**Describe the solution you'd like**
We would like edit the values in the cronjob template to define the number of job history to retain.
example - 
cronjobs.spec.failedJobsHistoryLimit, cronjobs.spec.SuccessfulJobsHistoryLimit.

**Describe alternatives you've considered**
We tried to add annotation to Cronjobs to work with kube-janitor, however we do not have the access to do the same.

**What version of eunomia are you using?**
0.1.7

</pre></details>

eunomia version:0.1.7

**Additional context**

**Comment by seanmalloy** [comment]
This will be considered for the v1alpha2 API.
