### ISSUE TITLE
Eunomia will randomly delete objects when multiple jobs for the same CR run concurrently

### ISSUE THREAD

**Issue by sanbornick** [KohlsTechnology/eunomia#370]
Just stubbing this in now so we have an issue to track all the stuff going on around this. Will update later.

**What version of eunomia are you using?**
All versions are affected

**Does this issue reproduce with the latest release?**
Yes

**What operating system and processor architecture are you using (`kubectl version`)?**
All os/arch are affected

**What did you do?**
Create a CR with multiple triggers such as a cron + webhook

**What did you expect to see?**
My resources to get managed without issue.

**What did you see instead?**
Some resources are randomly deleted. They will get recreated on a subsequent run, but they were removed in the interim. This can result in loss for things that had state, such as PVC's. When considering deletion chaining, if the object affected is a namespace or a gitopsconfig CR with deletion mode set to delete many resources can be deleted and dramatic outages caused.

**FOR THIS REASON WE DO NOT RECOMMEND RUNNING EUNOMIA IN ANYTHING OTHER THAN EXPERIMENTAL ENVIRONMENTS AS YOU WILL HAVE OUTAGES AND DATA LOSS.**

**Comment by sanbornick** [comment]
#339 is an example of what happens when a given CR manages itself, and then this bug is encountered for the CR object and the resourceDeletion mode is set to delete, resulting in a worst case scenario where Eunomia randomly deletes everything a CR manages.

**Comment by sanbornick** [comment]
#351 was an implementation of a short term solution to reduce the chances for hitting the overall job race condition, but since it doesn't introduce a lock it is still possible to encounter other races. If multiple instances are running concurrently the second one started would eventually delete all the resources the second one updated due to the timestamp label needing to match. By changing that to less than or equal to resources that were managed during the overlap of the jobs is no longer affected.

We did not include logic to skip resources determined to already be updated, which might seem natural to include in this, as there is still a race for individual resources. In the absence of a lock mechanism putting in skip logic would dramatically increase the frequency that much smaller race window is encountered so likely would still have very detrimental effects, or possibly even be worse.

**Comment by seanmalloy** [comment]
See this comment for some details on how to fix this ... https://github.com/KohlsTechnology/eunomia/issues/339#issuecomment-700230586

**Comment by vinny-sabatini** [comment]
The current state of the race condition is as follows:

- Job A starts right before Job B
- Job B finishes applying resources before Job A, which means all resources would have Job A's timestamp
- Job B gets to the point where it tries to delete resources, and the resource timestamp is then less than the job's timestamp, which would result in Job B deleting the resources.

From the article mentioned in https://github.com/KohlsTechnology/eunomia/issues/339#issuecomment-700230586, it looks like we could use the `metadata.resourceVersion` field as a locking/concurrency protection mechanism. The job would retrieve the `resourceVersion` from all the resources the job wants to apply and append that value into the yaml definition. Then when the job applies the resources, if the `resourceVersion` match what is in etcd, the resource will be applied, but if it does not match, the apply will fail.
