### ISSUE TITLE
Unable to build Eunomia on current version of operator-sdk

### ISSUE THREAD

**Issue by vinny-sabatini** [KohlsTechnology/eunomia#373]
**What version of eunomia are you using?**

eunomia version: v0.1.8

**Does this issue reproduce with the latest release?**
Yes

**What operating system and processor architecture are you using (`kubectl version`)?**

<details><summary><code>kubectl version</code> Output</summary><br><pre>
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.2-0-g52c56ce", GitCommit:"d7f3ccf9a5bdc96ba92e31526cf014b3de4c46aa", GitTreeState:"clean", BuildDate:"2020-09-16T16:46:07Z", GoVersion:"go1.13.4", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.1", GitCommit:"206bcadf021e76c27513500ca24182692aabd17e", GitTreeState:"clean", BuildDate:"2020-09-14T07:30:52Z", GoVersion:"go1.15", Compiler:"gc", Platform:"linux/amd64"}
</pre></details>

**What did you do?**

I pulled the latest code base of Eunomia and ran `make build`

**What did you expect to see?**
Eunomia to successfully build

**What did you see instead?**
An error when it was trying to pull all of the necessary dependencies, `github.com/operator-framework/operator-sdk` in particular:
```
$ make build
# Future Item: remove the use of `go mod vendor`
go mod vendor
warning: ignoring symlink $HOME/go/src/github.com/KohlsTechnology/Eunomia/deploy/helm/eunomia-operator/crds
go: github.com/operator-framework/operator-sdk@v0.12.1-0.20191112211508-82fc57de5e5b requires
        github.com/operator-framework/operator-registry@v1.1.1 requires
        bitbucket.org/ww/goautoneg@v0.0.0-20120707110453-75cd24fc2f2c: reading https://api.bitbucket.org/2.0/repositories/ww/goautoneg?fields=scm: 404 Not Found
make: *** [build] Error 1
```

It seems a dependency of v0.12.1 of the Operator-SDK (bitbucket.org/ww/goautoneg) has been deleted or moved.

**Comment by Smiley73** [comment]
@vinny-sabatini a large amount of work for this is already done: https://github.com/KohlsTechnology/eunomia/pull/342

**Comment by seanmalloy** [comment]
Also, we need to use a `vendor` directory too. Otherwise this could happen again.

Also, now we can't go back and rebuild older releases. :-(

**Comment by vinny-sabatini** [comment]
I attempted to fix this dependency but go mod did not seem to like it (based on findings here - https://github.com/openshift/odo/issues/3983):
```
# Change made to go.mod
require(
...
)

replace bitbucket.org/ww/goautoneg => github.com/munnerz/goautoneg v0.0.0-20120707110453-a547fc61f48d

// Pinned to kubernetes-1.15.4
replace (
...

$ go mod tidy
warning: ignoring symlink /Users/tkmaey0/projects/go/src/github.com/KohlsTechnology/Eunomia/deploy/helm/eunomia-operator/crds
go: github.com/munnerz/goautoneg@v0.0.0-20120707110453-a547fc61f48d used for two different module paths (bitbucket.org/ww/goautoneg and github.com/munnerz/goautoneg)
```
I have not been able to figure out how to get around this next error.
