### ISSUE TITLE
Hashicorp Vault Integration

### ISSUE THREAD

**Issue by Smiley73** [KohlsTechnology/eunomia#43]
## What happens?
We need to have the ability to pull secrets and inject them into the templating engine. We need to decide on what the best approach for this is.

## What were you expecting to happen?
We determine a way to integrate Hashicorp Vault in a way that will allow adding other secrets management solutions in the future.

**Comment by raffaelespazzoli** [comment]
I'd like to understand this requirement better.
Is this like saying that some of the parameters are not coming from the parameter git repo, but actually from a secret store?
That would probably mean that we need to turn the parameter source into an array of potentially different sources. Also it escapes me how secrets will be merged with normal parameters and then used by the templating engine.

**Comment by Smiley73** [comment]
Yeah nobody said it's going to be easy to solve. ;-)

We need the ability to inject secrets from Hashicorp Vault, because that's the best place to store them. We can't put them in github.

I've been doing some research and it might be best to write a helm plugin, which does exactly that. This would allow for supporting different secret backends in the future and also make it independent from the eunomia code base.

A lot of the more advanced and flexible features might require us to restrict them to a templating engine that can support it. I'm right now thinking that helm is the answer for a lot of these problems. The variable hierarchy has a similar potential solution.

**Comment by Smiley73** [comment]
Please hold off on working on this item. A solution will soon be available.

**Comment by seanmalloy** [comment]
`Please hold off on working on this item. A solution will soon be available.`

What exactly do you mean? Can you provide more details?

**Comment by Smiley73** [comment]
@seanmalloy I can't share the information in public. Talk to me in person.

**Comment by nabadger** [comment]
I'm wondring why would you need to tie in secrets injection into the gitops/operator / templating at all.

There's quite a few projects around now that can do this at the Deployment/PodSpec level (check out some of the tools avialable from the bankvaults project). 

Non-vault solutions tend to focus around tools like SealedSecrets from bitnami.

**Comment by Smiley73** [comment]
I don't care how we support it at the end, we just need to provide the capability. I'm thinking this is more a case of "here are some ways to solve this" in our docs.

**Comment by fabstu** [comment]
Did anything come of this @Smiley73 ? I did not find any further reference.

**Comment by seanmalloy** [comment]
@fabstu the eunomia project has not decided on the best way to implement this feature. Please feel free to share any ideas or recommendations you have. Thanks!

**Comment by fabstu** [comment]
@seanmalloy Difficult! I don't have much of an idea either. Just wondered whether anything came of the prior discussion : )

**Comment by Smiley73** [comment]
@fabstu our current workaround is to use vault init containers for the pods that need the secrets. 

We have some ideas for v1alpha2 to be able to inject secrets before the k8s resources are modified. Unfortunately the the v0.2.x release of Eunomia is still a bit out. (We could use some help squashing bugs to make faster progress ;-) ).

**Comment by fabstu** [comment]
Thanks for the info @Smiley73.

I don't habe the time to spare, but I think having different template files is an interesting way to do things compared to flux.
