### ISSUE TITLE
Ability to push config without direct GitHub access

### ISSUE THREAD

**Issue by Smiley73** [KohlsTechnology/eunomia#44]
## What happens?
Kubernetes clusters without internal network access can not be managed.

## What were you expecting to happen?
Kubernetes clusters that do not have a connection to the internal network, need to be somehow able to receive the configuration from an internal GitHub. Maybe introduce some kind of proxy or push-model.

**Comment by raffaelespazzoli** [comment]
Can we have more information on this use case? 
It looks like we are saying that the gitops operator needs to be able to work without having access to the git server... Or with "internal gitops" are we meaning a git server installed internally on the cluster?

**Comment by Smiley73** [comment]
One of our potential internal customers leverages our cloud provider's kubernetes offering. That one does not have access to the internal network and thus can't get to GitHub. It would be ideal if we could still use the operator, but keep the repos internally for security reasons. If you want to know more then I can share it on our call. I can't post the technical details on a public forum like this.
