### ISSUE TITLE
Add Variable Hierarchy to GitOpsConfig CR

### ISSUE THREAD

**Issue by seanmalloy** [KohlsTechnology/eunomia#5]
## What happens?

I would like to be able to use a hierarchy of variables for the process template step.

## What were you expecting to happen?

In a GitOpsConfig CR I can specify a hierarchy of variables. The template processor will handle processing the hierarchy of variables.

## Steps to reproduce: 

* N/A

## Any errors, stacktrace, logs? 

N/A

## Environment:

* Runtime version(Java, Go, Python, etc): N/A
* Desktop OS/version: N/A

## Additional comments:

Examples of variable hierarchies that already exist in the wild ...
* https://github.com/gnuthought/openshift-provision-demo#resource-hierarchy
* https://puppet.com/docs/puppet/5.4/hiera_intro.html

**Comment by seanmalloy** [comment]
Also need the ability to pass a blob of structured data in the GitOpsConfig spec to specify the hierarchy. This is an alternative to a list of variables.

**Comment by Smiley73** [comment]
Came across this project that might help us merge the yaml files with the parameters: https://github.com/imdario/mergo

**Comment by Smiley73** [comment]
I did some more research and this might already be directly supported in helm. We have to test it out: https://github.com/helm/helm/issues/3486
Otherwise there's actually a plugin for helm to leverage hiera, which might be even more desired: https://github.com/cststack/k8comp

**Comment by Smiley73** [comment]
Here's another approach, which would simply be a different templating engine: https://github.com/deepmind/kapitan

**Comment by Smiley73** [comment]
I'm wondering if we should stick with the original idea and simply make parameter source a list with a defined priority. We would simply use `yq` to merge the files in the specified order. This way the hierarchy can span repos.

**Comment by seanmalloy** [comment]
The initial, but not final implementation was created as part of #156. Additional work is needed to make the hierarchy feature GA.
