### ISSUE TITLE
Provide cluster roles to manage CRs

### ISSUE THREAD

**Issue by Smiley73** [KohlsTechnology/eunomia#53]
## What happens?
It doesn't seem to be sufficient to be an admin of a namespace (at least on OpenShift 3.11) to view the GitOpsConfig CRs.

## What were you expecting to happen?
We should provide roles that will allow viewing and managing CRs. Viewing might be more important, because any of the CRs should be managed via GitOps anyway.

**Comment by sanbornick** [comment]
Aggregate to admin, edit, and view? How should the roles get applied? Should that be automated? Should that be different if the operator is installed namespaced?

**Comment by Smiley73** [comment]
I'm thinking about keeping it simple right now and providing an admin and view role. I created 2 basic ones and will submit them soon with my helm installer PR.

**Comment by sanbornick** [comment]
Meant for human use or by the operator? 

> because any of the CRs should be managed via GitOps anyway.

Do you intend for a given CR the operator is operating on to manage itself? Or is that intended to be managed by an upstream CR? Former there's a bootstrapping problem, latter you've got an location/ownership issue.

**Comment by Smiley73** [comment]
We already have a custom role (both cluster and namespace) for the operator itself. So this one is just intended for people access.
It could be owned by an upstream CR, but that adds a whole new set of issues. We need to first get some runtime on it to determine what the best ways of managing it will be. We might have to split this out into two different charts in the future, one that requires cluster-admin and one that doesn't. 
I want to keep this simple for now, until we learn more.

**Comment by Smiley73** [comment]
@sanbornick I thought of this and think we should separate it right now. It'll be a much more realworld-ish approach. Stay tuned for an updated PR...

**Comment by Smiley73** [comment]
@sanbornick I added the role aggregation. It'll be part of the larger PR

**Comment by vinny-sabatini** [comment]
Friendly reminder to remove this block when this issue is figured out.
https://github.com/KohlsTechnology/eunomia/pull/67/files#diff-2fce78a7f7833e3b8b8a8087cc964131R69-R83
