### ISSUE TITLE
Need ability to specify namespace in CR

### ISSUE THREAD

**Issue by Smiley73** [KohlsTechnology/eunomia#55]
## What happens?

Currently all resources get created within the namespace the job runs in. This makes it impossible to e.g. create a new namespace, create a new SA and CR within it, then have the operator take it from there.

## What were you expecting to happen?

We can create resources in any namespace, as long as the SA has sufficient access.
We should extend the CRD and add:
```
spec:
  namespace: "xxx"
```
That defaults to the current namespace if it's not defined.
The job templates, and `discoverEnvironment.sh` and `resourceManager.sh` need to set the proper context.

This can simply be passed as an ENV variable to the jobs. The variable already exists, but is not consumed.
```
{{ if .Config.Spec.namespace }}
              value: {{ .Config.Spec.namespace }}
{{ else }}
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace          
{{ end }}
```

## Steps to reproduce: 

Try creating a resource in another namespace.

**Comment by sanbornick** [comment]
Namespaces are not namespaced resource so the operator would just need cluster scoped rights to create it. As far as other resources I think we need think about that more. I would be against implementing namespaces as a construct of the tool if we can do it intrinsically as part of the resource manifests.

**Comment by Smiley73** [comment]
It didn't seem that most resources support specifying a namespace, unless I screwed something up during my testing.

**Comment by Smiley73** [comment]
I must have had something misconfigured. It works as-is. Closing issue.
