### ISSUE TITLE
Create debug image of operator

### ISSUE THREAD

**Issue by sanbornick** [KohlsTechnology/eunomia#71]
(While submitting an issue briefly describe the problem you are facing or a new feature you would want to see added) 

## What happens?
Using distroless means we cannot debug inside the image if something is going wrong.
...

## What were you expecting to happen?
Ability to debug when necessary by deploying a debug version of the image with the tools necessary to debug and the operator binary running in debug mode.
...

## Steps to reproduce: 
N/A
* ...
* ...

## Any errors, stacktrace, logs? 
N/A
...

## Environment:

* Runtime version(Java, Go, Python, etc): N/A
* Desktop OS/version: N/A

## Additional comments:
N/A
...

**Comment by seanmalloy** [comment]
We could use `gcr.io/distroless/base:debug-nonroot`for the debug image.



gcr.io/distroless/static
