### ISSUE TITLE
e2e Tests Run Through Travis CI

### ISSUE THREAD

**Issue by seanmalloy** [KohlsTechnology/eunomia#72]
## What happens?

e2e test do not currently run through travis CI.

## What were you expecting to happen?

e2e tests run through Travis

## Steps to reproduce: 

N/A

## Any errors, stacktrace, logs? 

N/A

## Environment:

* Runtime version(Java, Go, Python, etc): Go 1.12
* Desktop OS/version: N/A

## Additional comments:

N/A

**Comment by etsauer** [comment]
Looks like one of the operator-sdk core members wrote a blog post on running minikube in travis. https://blog.travis-ci.com/2017-10-26-running-kubernetes-on-travis-ci-with-minikube
