### ISSUE TITLE
Eunomia-base image scripts don't handle errors well.

### ISSUE THREAD

**Issue by etsauer** [KohlsTechnology/eunomia#74]
While running through the Hello Worl Yaml sample I get multiple errors. First, it appears the scripts use `find` and `cat`, neither of which exist in the image. Additionally, if the script attempts to delete resources that don't exist, either because its looking in the wrong namespace, or because the resources were already deleted, the script fails, leaving the CR stuck in delete mode as the finalizer was never cleaned up.

## What happens?

Run through the [Hello World YAML](https://github.com/KohlsTechnology/eunomia/tree/master/examples/hello-world-yaml) example. Then manually delete the resources created:

```
kubectl delete deployments.apps/hello-world
kubectl delete svc/hello-world
```

Now delete the cr, and look at the jobs logs from the resulting job.

```
$ kubectl logs gitopsconfig-hello-world-yaml-w4tydf-nfzj4
Cloning Repositories
Cloning into '/git/templates'...
Cloning into '/git/parameters'...
Setting cluster-ralated environment variable
Context "current" created.
Switched to context "current".
error: the server doesn't have a resource type "route"
Processing Templates
Managing Resources
Context "current" modified.
Switched to context "current".
cat: can't open 'find': No such file or directory
No resources found
cat: read error: Is a directory
No resources found
cat: unrecognized option: i
BusyBox v1.30.1 (2019-06-12 17:51:55 UTC) multi-call binary.

Usage: cat [-nbvteA] [FILE]...

Print FILEs to stdout

	-n	Number output lines
	-b	Number nonempty lines
	-v	Show nonprinting characters as ^x or M-x
	-t	...and tabs as ^I
	-e	...and end lines with $
	-A	Same as -vte
No resources found
cat: can't open '.*\.yaml': No such file or directory
No resources found
Error from server (NotFound): error when deleting "/git/manifests/hello-world.yaml": deployments.apps "hello-world" not found
Error from server (NotFound): error when deleting "/git/manifests/hello-world.yaml": services "hello-world" not found
```

## What were you expecting to happen?

...

## Steps to reproduce: 

* ...
* ...

## Any errors, stacktrace, logs? 

...

## Environment:

* Runtime version(Java, Go, Python, etc):
* Desktop OS/version:

## Additional comments:

...

**Comment by Smiley73** [comment]
This might be an easy fix by just adding those 2 missing binaries to the base image.
`apk install find cat` might do the trick (guessing). Are you planning to send in a PR for it or should I take a look?

**Comment by etsauer** [comment]
@Smiley73 I'll work on it.

**Comment by Smiley73** [comment]
This could be a problem related to our proxy here at Kohl's. The code is there in the dockerfile, but fails to pull. Need to try the build-images.sh script outside of our network.
Here's how I'm testing:
```
minikube start
eval $(minikube docker-env)
./scripts/build-images.sh quay.io/kohlstechnology
```

The base image build should correctly download and install the packages, but doesn't seem to do so. The image build should actually fail, not sure why it doesn't.

**Comment by Smiley73** [comment]
Well the image build script had no error handling: https://github.com/KohlsTechnology/eunomia/pull/75

**Comment by Smiley73** [comment]
@etsauer what did you test this on? I can't even get it try spin up the job to delete the resources. It just hangs (finalizer issue). I'm using the latest minikube.

**Comment by seanmalloy** [comment]
Related to #52
