### ISSUE TITLE
All scripts and Dockerfiles should use same variables

### ISSUE THREAD

**Issue by Smiley73** [KohlsTechnology/eunomia#77]
Currently we have variables defined in many different places (e.g. kubectl version). We need to make sure we're consistent and pull it all from the same sources. Maybe travis.yml is the right place?

## What happens?
If we change a version, we have to change it in many places and most likely will forget one.

## What were you expecting to happen?
Changing a version is a simple task in one file.

**Comment by etsauer** [comment]
@Smiley73 can you provide some examples?

**Comment by Smiley73** [comment]
Just some random examples. I'm sure there are more...

https://github.com/KohlsTechnology/eunomia/blob/master/scripts/build-images.sh#L19
https://github.com/KohlsTechnology/eunomia/blob/master/scripts/images-pull-push.sh#L21
https://github.com/KohlsTechnology/eunomia/blob/master/template-processors/base/Dockerfile#L6
https://github.com/KohlsTechnology/eunomia/blob/master/template-processors/helm/Dockerfile#L4

**Comment by seanmalloy** [comment]
The release version variables will get cleaned up as part of #64. I think the `scripts/images-pull-push.sh` script can probably be removed. I don't think we need this.
