### ISSUE TITLE
Could we build our base images on an image that uses glibc rather than musl?

### ISSUE THREAD

**Issue by etsauer** [KohlsTechnology/eunomia#78]
The Alpine base image we use for the template processors uses musl c libraries instead of the gnu c libraries. As such, some dynamically linked binaries, such as oc do not work without some re-linking. This is what I had to do to get oc minimally working on our base image:

```
  && ln -s /lib /lib64 \
  && ln -s /lib64/ld-musl-x86_64.so.1 /lib64/ld-linux-x86-64.so.2
```

This makes me nervous as, while this appears to work, it would not be community supported should we experience issues.

I would suggest we switch to using one of the [Universal Base Images](https://www.redhat.com/en/blog/introducing-red-hat-universal-base-image) as they are rhel based, but still fully community distributable. I think something like [ubi8/ubi-minimal](https://access.redhat.com/containers/?tab=overview#/registry.access.redhat.com/ubi8/ubi-minimal) would work nicely for us.

**Comment by Smiley73** [comment]
@etsauer this is where we originally started, but even the minimal UBI still is pretty big. UBI8 wasn't available yet, so not sure if that's any better.

**Comment by Smiley73** [comment]
I guess I should have checked first... 32MB isn't bad. It might be okay switching back.

**Comment by seanmalloy** [comment]
We should consider offering to separate types of images, a full featured image that includes debugging tools and a very light weight image.

**Comment by seanmalloy** [comment]
Close by #114
