### ISSUE TITLE
build-images.sh does not bump latest tag upon GitHub release

### ISSUE THREAD

**Issue by vinny-sabatini** [KohlsTechnology/eunomia#81]
## What happens?
If you create a new release, only the version tag will be created, latest is not updated.

## What were you expecting to happen?
If a release is created, the version tag should be created and the latest tag should be updated.

## Steps to reproduce: 
Create a release in GitHub and check the quay.io repository for the images.  The latest tag will not change

## Any errors, stacktrace, logs? 
N/A

**Comment by seanmalloy** [comment]
I think this is actually the expected behaviour. Every merge to master or every release created should push to the `latest` tag in quay.io.
